#+title: Méthode de sélection et de configuration des représentations graphiques des corpus d'informations
#+author: Cyprien PIERRE \orcidlink{0009-0009-9040-6795}
#+EMAIL: cyprien.pierre@eiffage.com
#+DATE: {{{time(%Y-%m-%d)}}}
#+setupfile: "config.org"

# Rédigé sur Emacs en Org-mode,
# Edité avec AUCTeX sur la distribution TeX Live via le compilateur XeLaTeX

#+begin_abstract
Rédiger l'abstract ici
#+end_abstract

\renewcommand{\keywordsname{\textbf{Mots clés : }\keywords{Visualisation de données, Graphique, Méthode}

#+LaTeX: \begin{multicols}{2}

* Introduction
La visualization de donnée est une discipline ancienne à la littérature riche et précise. Cependant, il n'existe, à ce jour pas de synthèse opérationnelle ni de méthode harmonisée dans la conception des représentations graphiques des informations. Ce rapport vise à fournir un point de départ cohérent à de futurs travaux en représentation visuelle d'informations. Il est basé sur une revue de littérature rigoureuse et les recommendations qu'il porte sont issues des lectures réalisées. Une tentative est réalisée d'objectiver les usages des diverses représentations.

L'origine de ces travaux prend place dans un besoin grandissant de solution de visualization d'information dans le secteur de la construction. Les technologies de Big Data, BIM, VDC et les disciplines de la science des données ont fortement pénétré ce secteur sur l'ensemble du cycle de vie des ouvrages. [cite:@asiauniversitytaichungtaiwanResearchApplicationFunctiontechnologyaesthetics2020] =mentionner les jumeaux numériques ici= L'utilisation renforcée de l'IoT, l'émèrgence des BIS et BOS et l'intégration des solutions d'intelligences artificielles renforcent d'autant plus la nécessité pour ce secteur de se doter de moyens robuste en exploration et en communication des informations.

Le secteur de la construction est historiquement peu digitalisé en comparaison avec les autres industries.[cite:@REF???] Pour adresser ce retard, il est important de publier des études opérationnelle claires et industrialisables dont chaque acteur puisse bénéficier immédiatement. Ce rapport s'inscrit dans cette démarche.

Il existe de multiples manières d'interargir avec un graphique. [cite:@schwabishCenteringAccessibilityData2022a;@frankelavskyRightToolsJob2022]

Ce rapport aborde les éléments impliquant la mise en oeuvre de solution programmatique d'accessibilité et pouvant intégrer une logique globale de préparation de graphiques numériques tels que:
- L'exploration visuelle,
- La lecture des tables,
- L'écoute des descriptions,
- La sonification des données,
- L'interractivité avec les commandes de clavier.

Ce rapport n'aborde pas les éléments nécessitant l'emploi de matériels spécifiques tels que :
- L'exploration en réalité étendue,
- L'utilisation de retours haptiques,
- L'emploi d'écran à relief (braille).

* Démarche
La conduite de cette revue s'est déroulé de la manière suivante :
Nous avons commencé par dresser un panorama des types de graphiques existant en nous appuyant sur les travaux de "From Data to Viz"[cite:@yanholtzDataViz2018], "The Graphic Continuum"[cite:@jonathanschwabishGraphicContinuum2014], "Lexique Visuel"[cite:@alansmithLexiqueVisuel], "Insights for ArcGis"[cite:@lindabealeInsightsArcGIS2017].
Cette première action nous a permis de pré-catégoriser les graphiques selon leurs utilisation.

Ensuite, nous avons étudié les livres de divers auteurs et en avons tirés un ensemble de rêgles générales quant à la préparation des graphiques. Cela concerne les aspects visuels (couleurs, polices...), des conseils sur la pertinence dans le choix des types graphiques suivant les objectifs attendus, quelques éléments d'accessibilités et des retours d'expériences. Sur cette base, nous avons affiné la catégorisation préétablies et commencé à regrouper les recommendations.

Pour compléter les dispositions propres à l'accessibilité, nous avons étudié le rapport "Centering accessibility in data visualization". [cite:@schwabishCenteringAccessibilityData2022] Nous en avons tiré un apperçu global des approches possibles pour améliorer l'accessibilité des graphiques ainsi que de nombreux conseils et bonnes pratiques.

En parallele, nous avons étudié diverses chartes de publications issues de divers médias et institutions. Ces lectures nous ont permis de nourrir les reccommendations en matière de conception visuelle des graphiques ainsi que de dresser une liste d'éléments standardisables et d'autres pouvant être laisser libre de personnalisation avec quelques conseils.

Pour finir, nous avons étudié les articles scientifiques publiés sur ces sujets avec une profondeur de recherche à 5 ans. Ce choix de profondeur résulte d'une évolution conséquente depuis le début de la décenie des sciences de l'information. Cetains papiers étudiés sont plus anciens mais ont été très régulièrement cités par d'autres publications et nous avons choisis de les considérer. De cette étape, nous avons affiné les recommendations en identifiant les résultats d'expérimentations.

* Sémantique
* Polices
Le choix d'une police de texte a de multiples impacts sur la perception des graphiques. Il convient de selectionner une police accessible et de préférence sans sérif pour un usage informatique (Arial, Calibri, Source Sans Pro, Verdana...). [cite:@andreaskrauseBestPracticesData2024] Les polices avec serif peuvent être considérés pour la production d'éléments imprimés. Il n'y a pas de consensus clair sur l'impact des sérifs sur l'accessibilité des polices. [cite:@stephenfewTableDesign2012] Il n'y a pas non plus de consensus clair sur l'efficacité des polices conçues pour adresser des problématiques d'accessibilités telles que la dyslexie. Il convient d'utiliser une police utilisant une hauteur fixe pour les chiffres. [cite:@stephenfewTableDesign2012]

Il est conseillé de restreindre l'utilisation de l'italique car les textes affichés de la sorte sont plus difficiles à lire. Il est également conseillé de limiter l'utilisation de la graisse et du soulignement à des cas spécifiques pour ne pas surcharger les présentations.

La taille de la police joue un role majeur dans l'accessibilité du texte. Il est recommendé d'utiliser une hauteur de police de 12 points.[cite:@andreaskrauseBestPracticesData2024] Le nombre de tailles et de type de police doit être limité en nombre.[cite:@andreaskrauseBestPracticesData2024]

Certaines polices peuvent être utilisés pour projeter des icones (NerdFont, StateFace...).[cite:@jonathanschwabishQualitative2021] L'intérêt des icones est discuté plus tard dans ce rapport.

Il est important de prévoir le chargement de toutes polices non standard (eg. Source Sans Pro, NerdFont...) dans l'interface utilisateur si celles-ci sont utilisées puisqu'elles ne sont probablement pas installées dans le système d'exploitation de l'utilisateur. Prévoir leurs chargement vise à assurer la bonne expérience des utilisateurs.

* Couleurs
L'utilisation de la couleur n'est pas nécessaire pour éditer un graphique efficace. Il s'agit par exemple de la manière la moins efficace pour représenter des différences entre des variables. [cite:@Beecham2021]

Cependant, utilisé convenablement elle peut aider à la transmission des informations, améliorer la lisibilité de certain graphiques, inscrire une identité visuelle ou encore succiter l'intérêt du lecteur. L'objectif des représentations graphiques des informations étant de maximiser les chances d'acquisition d'une information par un lecteur, il est important de succiter son intérêt en premier lieu. [cite:@Références sur l'esthétisme?]

La conception de palettes de couleurs est un exercice difficile. Cette opération implique de considérer les facultées de perception visuelle des utilisateurs mais également le médium et les habitudes associées.

Les études de (Tran et al. 2024) ont mis en évidence une efficacité particulière de l'utilisation du vert vis à vis du rouge et du bleu dans la vitesse de transmission des informations. L'écart n'est cependant pas suffisement significatif pour justifier à ce titre de l'abandon de l'utilisation de l'une ou l'autre des couleurs. 

Pour créer une palette de couleur accessible, celle-ci doit être adaptée à :
- L'achromatopsie, prévalence de 0.003% de la population et par extension, à l'impression en noir et blanc,[cite:@andreaskrauseBestPracticesData2024]
- La deutéranopie, prévalence de 1.27% des hommes et 0.01% des femmes,
- La protanopie, prévalence de 1.01% des hommes et 0.01% des femmes
- La deutéranomalie, prévalence de 4.63% des hommes et 0.36% des femmes
- La protanomalie, prévalence de 1.08% des hommes et 0.03% des femmes
- La tritanopie, prévalence de 0.003% de la population
- La tritanomalie, prévalence de 0.01% de la population
source : https://lesyeuxdudaltonisme.fr/les-types-de-daltonisme/

Des outils comme [[https://gka.github.io/palettes/#/5|s|ce0072,96ffea,00ffad|ffffe0,ff005e,93003a|1|1][Color Palette Helper]] permettent de vérifier le comportement des palettes de couleurs au regard de certaines affections visuelles.

Elle doit également éviter les biais sociologiques, cognitifs, culturels, et autres tels que le genrage des couleurs (bleu, rose),[cite:@andreaskrauseBestPracticesData2024]la perception morale (vert, rouge),[cite:@article sur le rouge en chine] ou la valeur émotionnelle (rouge).[cite:@tranDiscoveringAccessibleData2024]

L'utilisation de la couleur doit également respecter le principe de [citer le principe sur l'encre de Tufte]. Ainsi, il convient de ne pas remplir les larges zones avec une couleur saturé.[cite:@wilkeCommonPitfallsColor2019] Si un remplissage est requis par le type de graphique, il est préférable d'utiliser des couleurs moins saturés et d'y ajouter de la transparence. [cite:REF???] 

#+caption: Palette d'évidence
#+name: fig:Pal-a
#+attr_latex: :placement [H]
[[./img/palette-evidence.pdf]]

Cette palette de couleur permet d'orienter le regard du lecteur directement sur le segment du graphique important pour l'acquisition de l'information.[cite:@andreaskrauseBestPracticesData2024]

Lors de l'emploi de la palette d'évidence il est important que la couleur de base n'attire pas l'attention. Le focus de l'utilisateur doit rester sur l'élément accentué.[cite:@wilkeColorScales2019]
Le plus efficace est de tracer tous les éléments dans un gris homogène et léger et n'afficher que les valeurs accentuées avec la couleur retenue. [cite:@wilkeColorScales2019]

#+caption: Palette binaire
#+name: fig:Pal-b
#+attr_latex: :placement [H]
[[./img/palette-binaire.pdf]]

Permet de souligner un propos divergent suivant un facteur binaire.[cite:@jonathanschwabishDevelopingDataVisualization2021] 

#+caption: Palette divergente
#+name: fig:Pal-d
#+attr_latex: :placement [H]
[[./img/palette-divergente.pdf]]

Cette palette est utilisée pour accompagner la visualisation de la déviation de données dans deux directions opposées à un point central. [cite:@wilkeColorScales2019]

Il convient que les écarts de contraste des deux extrémitées avec le point central soit égal. Il convient également qu'il y ai le même nombre d'échelons colorés de part et d'autre du point central. [cite:@wilkeColorScales2019]

Il convient de ne pas utiliser le rouge et le vert conjointement comme teintes d'extrémités car environ 4% de la population ne peut pas discriminer ces couleurs. [cite:@schwabishCenteringAccessibilityData2022a]

Il convient d'utiliser un vérificateur de couleur pour valider la composition de cette palette.[cite:@andreaskrauseBestPracticesData2024]

#+caption: Palette monochrome
#+name: fig:Pal-m
#+attr_latex: :placement [H]
[[./img/palette-monochrome.pdf]]

Aussi appelée "séquentielle", cette palette de couleur est utilisée lorsque les données sont organisées dans un ordre quantitatif (croissant, décroissant, etc.). [cite:@wilkeColorScales2019;@jonathanschwabishDevelopingDataVisualization2021] 

Les variations réalisées en modifiant la lumiosité d'une teinte.[cite:@andreaskrauseBestPracticesData2024] 

En utilisant cette palette de couleur, l'utilisateur perçoit la valeur la plus contrasté (foncé) comme étant la plus haute et inversement. [cite:@REF???]

Il convient d'employer une graduation présente dans l'environnement natuel, partant par exemple d'un bleu foncé et évoluent vers un jaune clair. [cite:@wilkeColorScales2019]

#+caption: Palette thermique
#+name: fig:Pal-t
#+attr_latex: :placement [H]
[[./img/palette-thermique.pdf]]

C'est la température des couleurs qui souligne l'importance des données, du plus froid (faible) au plus chaud (élevé). [cite:@REF???]

En utilisant cette palette de couleur, l'utilisateur donnera plus d'importance aux zones de couleurs chaudes. [cite:@REF???]

#+caption: Palette catégorique
#+name: fig:Pal-c
#+attr_latex: :placement [H]
[[./img/palette-categorique.pdf]]
Ce jeu de couleur est utilisé pour discriminer des catégories et lorsque leurs divergences ou leurs ordre n'est pas important.[cite:@andreaskrauseBestPracticesData2024]

N'employez cette palette de couleur que lorsque les données affichées n'ont aucun lien intrinsèque. [cite:@wilkeColorScales2019]

Il convient d'utiliser un vérificateur de couleur pour valider la composition de cette palette.[cite:@andreaskrauseBestPracticesData2024]

#+caption: Palette arc-en-ciel
#+name: fig:Pal-x
#+attr_latex: :placement [H]
[[./img/palette-arc-en-ciel.pdf]]

Palette de couleur à prohiber.[cite:@wilkeCommonPitfallsColor2019]

* Tables
Une table ou tableur permet d'exposer des données brutes organisées en lignes ou en colonnes. [cite:@mikeyiHowChooseRight2020]

Sauf mention contraire, les recommendations sur les tables sont issues du livre "Show me the numbers" de Stephen Few.[cite:@stephenfewShowMeNumbers2012] L'auteur y rentre très en détails sur chaque point de paramétrage. Il y indique notamment les orientations en matière de construction de tableur lorsqu'il s'agit du choix premier d'affichage de données. Ce rapport s'intéresse à la conception de graphique. Dans ce cadre, les tableurs sont des éléments complémentaires pouvant être affichés par l'utilisateur pour explorer plus précisement les données préalablement affichées.

Des prescriptions spécifiques à la préparation de tableurs pour certains graphiques sont apportés le cas échéant dans la suite de ce rapport.

** Composition
Il est recommendé de séparer les entrées avec un espace vide.
Lorsque les données sont présentées en colonnes, l'espace entre deux colonnes doit être plus grand qu'entre deux lignes,
Lorsque les données sont présentées en ligne, l'espace entre deux ligne doit être plus grand qu'entre deux colonnes,

Insérer une ligne vide toutes les 5 lignes pour faciliter le balayage visuel. [cite:@NFENISO9241-125ErgonomieLinteractionHommesysteme2017]

Utiliser une ligne horizontale pour séparer les entêtes de colonnes des données,

Utiliser une ligne horizontale pour séparer les catégories lorsque les données sont triées par catégories et, ne pas répéter le nom de la catégorie sur toutes les lignes. Les noms des catégories doivent être dans la première colonne, les sous-catégorie dans la seconde colonne, etc. S'il y a plusieurs subdivisions, les noms des catégories doivent être apposées sur la même ligne.

Il convient de rappeler le nom de la catégorie en cas de changement de page et de maintenir la structure du tableur sur toutes les catégories et de rappeler les titres des colones en cas de changement de page.
Les catégories doivent être ordonnées suivant un ordre logique (eg. chronologique, alphabetique, par classement, etc.)

Ne pas effectuer de rotation sur un tableur, son orientation doit respecter celle du texte du document.

Maintenir les aligmnements les titres avecc celui des données en colonnes.

** Chiffres
Aligner les chiffres à droite.
Homogénéiser les décimales (généralement 2 ou 3 décimales suffisent suivant le contexte).
Indiquer les valeurs négatives avec le symbole "moins" (-), ici la notion de valeur symbolique est importante. Certains choisissent d'identifier les valeurs négatives entre parenthèses, cependant il ne s'agit pas d'une représentation naturelle répendue pour une telle identification.
Séparer les digit d'un nombre par un espace tous les 3 charactères. Dans le cas de grands nombres, il convient de les arrondir à la précision utile (dixaine, centaine...). Par défaut, la précision affichée doit correspondre à celle de la source d'information.
Si une valeur numérique réfère à une information de catégorie elle doit être traitée comme un texte.

** Texte
Aligner les textes à gauche.
Centrer les dates et utiliser une convention stricte d'écriture de ces données telles que "YYYY-MM-DD". [cite:@ISO8601-1DateHeureRepresentations2019] La composition de la date doit être indiqué à l'utilisateur. Le choix du format doit respecter le niveau de précision associée à la mesure. Implicitement, le choix d'un formatage de plus haut niveau que la précision de la mesure induit une agrégation des valeurs.
Centrer les données dont la largeur de charactère est fixe.

** Sommaire et agrégats
Utiliser une ligne verticale pour séparer les valeurs placées en colonne à droite de toutes les valeurs.
Utiliser une ligne horizontale si ces valeurs sont placées en une ligne en bas du tableau.
Si ces valeurs sont le message important de votre tableur, il convient de les affichés imédiatement à droite des colonnes de catégories ou immédiatement en dessous des entêtes de colonnes, suivant la nature du sommaire.

Les produits d'un calcul doivent être affichés dans la colonne imédiatement à droite de la colonne source de données.

** Mise en évidence
Si des valeurs spécifiques doivent être mises en avant, il est possible d'utiliser l'une ou l'autre de ces solutions :
- mettre le texte en gras,
- remplir la cellule d'une couleur.
Il est recommandé de limiter cette opération à un nombre réduit de valeur. Si cela n'est pas possible, il convient de sélectionner un autre mode de visualisation.

* Méthode de sélection

* Graphiques
** Arbre de mot
:PROPERTIES:
:en-name: Treeword
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:
Représente les liens sémantiques. Utilisé pour classifier les réponses textuelles d'une enquête.(voir Paige Jarreau) Utilisé pour illustrer l'usage des mots dans un texte.(voir Martin Wattenberg & Fernanda Viegas 2007) La taille des mots représente la fréquence de leurs usages. [cite:@jonathanschwabishQualitative2021]

** Arc
:PROPERTIES:
:en-name:
:chart-goal: Partie d'un ensemble
:data-type-x:
:data-type-y:
:END:
+Hémicycle, souvent utilisé pour visualiser la composition d'un effectif.+

** Arc temporel
:PROPERTIES:
:en-name: Arc-time
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:

Utilisé pour illustré les connexions des catégories à travers le temps. L'ordre des données influence la percéption de l'importance des connexions. [cite:@jonathanschwabishRelationship2021]

Peut être utilisé pour illustrer les distances entre deux points. Cet usage met bien en évidence l'augmentation des disances. [cite:@jonathanschwabishRelationship2021]

** Bande de valeur
:PROPERTIES:
:en-name: Strip plot
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Affiche les points de données d'une catégorie.[cite:@jonathanschwabishDistribution2021] Les valeurs peuvent être affichés par des lignes ou des cercles pleins mais les cercles sont à privilégier lorsqu'il est nécessaire de déagglomérer les données.

Il est possible d'utiliser de la transparence pour illustrer les zones de valeurs compactes. [cite:@jonathanschwabishDistribution2021] Utilisez la palette de couleurs divergentes [[fig:Pal-d]] pour mettre en évidence la répartition des valeurs mesurées et souligner la séparation de celles ci par rapport à un axe de référence.[cite:@jonathanschwabishDistribution2021]

Les points peuvent être légèrement décalés les uns des autres par un offset pour éviter le masquage de données par surimposition. Ce mode de représentation est appelé "essaim d'abeille" (beeswarm). [cite:@jonathanschwabishDistribution2021]

# -----à creuser-----
Histopoint : Wilkinson dot plot (Leland Wilkinson) Affichage des bandes de valeurs pour chaque agrégat d'un histogramme.[cite:@jonathanschwabishDistribution2021]

Epis de blé : Wheat plot (SFew)

** Barre divergente
:PROPERTIES:
:en-name:
:chart-goal: Déviation
:data-type-x:
:data-type-y:
:END:
Affiche correctement un ensemble de valeur quantitative triées par catégories lorsque des valeurs négatives sont utilisées. [cite:@alansmithLexiqueVisuel] L'axe des absysse doit être égal à 0 et toutes les barres doivent être projetées depuis cet axe.

** Barres divergentes empilées
:PROPERTIES:
:en-name:
:chart-goal: Déviation
:data-type-x:
:data-type-y:
:END:
Utilisé pour illustrer les résultats d'enquêtes impliquant un sentiment. [cite:@alansmithLexiqueVisuel] Les barres doivent être calculées en pourcentage et alignées à 100% comme pour une partie d'un ensemble. Les réponses sont affichées de façon ordonée et du plus négatif au plus positif. Il convient d'utiliser une palette de couleur divergente. Lors de la préparation d'une enquête impliquant des sentiment, il est conseiller de proposer un choix de valeur paires pour éviter les votes neutres sauf si la représentation de l'indiférence est une volontée de l'étude. De plus, *expliquer la limite de nombre de zones facile à visualiser* (max 6?)

** Barre empilées
:PROPERTIES:
:en-name: Stacked bar chart
:chart-goal: Comparaison
:data-type-x:
:data-type-y:
:END:
Représente le total de chaque catégorie et la proportion de leurs composantes. Les composantes doivent être homogènes. Si les proportions sont plus importantes que les totaux, considérer d'utiliser l'affichage empilée à 100%. [cite:@mikeyiHowChooseRight2020]

Seule la catégorie ayant sa base à 0 sera facile à comparer pour le lecteur car les autres ne partagent pas la même base.[cite:@jonathanschwabishComparingCategories2021] Il est préférable de tracer chaque diagramme de barre dans un grapgique distinct et des les disposer en [[matrice de graphique]]. [cite:@jonathanschwabishComparingCategories2021]

** Barre jumelée
:PROPERTIES:
:en-name:
:chart-goal: Comparaison
:data-type-x:
:data-type-y:
:END:
Permet d'afficher plusieurs séries. Devient plus difficile à lire avec plus de deux séries. [cite:@alansmithLexiqueVisuel]
Les barres d'une même catégories sont collées les unes aux autres pour souligner leurs appartenance à une même catégorie (ratio 1:0). Espacer les jeux de barres jumelées d'une largeur égale à une barre (ratio n:1).

Les barres sont colorées avec une palette de couleur de catégories. Les couleurs sont utilisées pour distinguées chaques barres dans une catégories, les couleurs doivent être homogènes pour chaque catégorie. Si les différentes valeurs affichées sont d'importances similaires, il convient d'utiliser une palette de couleurs à faibles contrastes. N'utiliser qu'une seule couleur par ensemble de données apparentées. [cite:@stephenfewComponentlevelGraphDesign2012]

** Barre ordonnée
:PROPERTIES:
:en-name:
:chart-goal: Classement
:data-type-x:
:data-type-y:
:END:
Les catégories sont ordonnées par décroissance de leurs valeurs de quantité[cite:@jonathanschwabishComparingCategories2021] sauf si les catégories on un autre ordre logique (eg. temporel). Dans ce second cas, cet ordre doit être utilisé pour la construction du graphique. [cite:@wilkeVisualizingAmounts2019]

*Note: si catégories temporelles, utiliser un histogramme?*

Lorsqu'un ordre de classement est à afficher, l'utilisation d'un graphique horizontal est à privilégier. [cite:@andreaskrauseBestPracticesData2024]

*William Playfair (1786) pionnier de l'utilisation de ce type de graph ?*

Les barres doivent être affichées à l'horizontal s'il y a beaucoup de valeurs à afficher ou si les labels des catégories s'entrevêchent. [cite:@alansmithLexiqueVisuel;@sosulskiGraphics2019;@wilkeVisualizingAmounts2019;@stephenfewComponentlevelGraphDesign2012;@jonathanschwabishComparingCategories2021]

Il convient de maintenir l'affichage vertical du graphique si les catégories affichées sont des unitées temporelles. [cite:@stephenfewComponentlevelGraphDesign2012]

Ce graphique est plus lisible pour un nombre limité d'entrées. [cite:@mikeyiHowChooseRight2020]

L'espace entre deux barres est égal à la moitié de la largeur d'une barre (ratio 1:0.5). Les barres ont toutes la même largeur. [cite:@stephenfewComponentlevelGraphDesign2012]

Utiliser une couleur homogène à l'ensemble des barres. Une couleur de contraste peut être utilisée pour mettre en évidence certaines catégories.

Ne pas utiliser de motifs de remplissage. Les barres doivent être remplies par un solide coloré. [cite:@stephenfewComponentlevelGraphDesign2012]

Ne pas utiliser de bordures de barres. Ces dernières doivent naturellement contraster avec l'arrière plan.

Si de grands écarts de valeurs empêchent la bonne visualisation des écarts sur une partie du graphique, il est recommendé d'ajouter un second graphique en barre ordonnée n'affichant pas les catégories aux grandes valeurs. [cite:@jonathanschwabishComparingCategories2021]

Ne pas afficher de séparateurs au niveau des catégories, les barres remplissent elles même ce rôle, associées aux espaces entres elles. [cite:@jonathanschwabishComparingCategories2021]

Pour les petits graphiques statiques, il convient d'apposer directement un label à chaque barre contenant la valeur de celles-ci. Par cette action, il convient également de masquer l'axe des absysses. [cite:@jonathanschwabishComparingCategories2021]

Pour les graphiques dynamiques, interractifs ou de grande largeur, il convient d'afficher des lignes d'aide à la lecture en projection des repères de l'axe des valeurs. Ces lignes doivent être faiblement contrastées et être tracées en arrière plan des barres. [cite:@jonathanschwabishComparingCategories2021]

Ne pas segmenter les barres. [cite:@jonathanschwabishComparingCategories2021]

Ne pas ajouter d'iconographie aux barres. [cite:@tranDiscoveringAccessibleData2024]

** Bulle proportionnelle ordonnée
:PROPERTIES:
:en-name:
:chart-goal: Classement
:data-type-x:
:data-type-y:
:END:
Utilisé pour illustrer les grandes variations de quantité pour différentes catégories et lorsque la distinction des nuances n'est pas primordiale. Les bulles doivent être dimensionnés par leurs surface pour éviter d'éxagérer les différences. [cite:@jonathanschwabishComparingCategories2021] Ce type de graphique utilise un double encodage de la quantité : la position et la taille. [cite:@wilkeVisualizingAssociationsTwo2019] Bien que ce type de représentation soit considéré comme engageant, il convient d'utiliser un graphique en barre ordonnée à la place lorsque l'évaluation des différences entre catégories est importante. [cite:@jonathanschwabishComparingCategories2021]

** Boite à moustache
:PROPERTIES:
:en-name:
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Résume les distributions multiples en montrant la médiane et l'étendue des données. [cite:@alansmithLexiqueVisuel]

Ce graphique est plus efficace lorsqu'il y a de nombreuses mesures pour une entrée et que leur distribution doit être représentée (eg : mesure médiane, basse, haute, incertitude...). [cite:@mikeyiHowChooseRight2020]

Les lignes s'étendant au dessus et en dessous sont appelées les moustaches. [cite:@wilkeVisualizingManyDistributions2019]

*Voir trx de son inventeur : John W. Tukey*

Il est possible d'afficher la position d'un point précis du jeu de donnée sous-jacent. (couleurs mise en évidence ?)

Les boites à moustaches suivent les dispositions graphiques des barres ordonnées. [cite:@stephenfewComponentlevelGraphDesign2012]

** Bosses
:PROPERTIES:
:en-name: Bumpchart
:chart-goal: Classement
:data-type-x:
:data-type-y:
:END:
Affiche l'évolution d'un classement entre différents jalons. [cite:@mikeyiHowChooseRight2020;@alansmithLexiqueVisuel]  Ce graphique n'affiche pas les valeurs sous-jacente mais uniquement le positionnement de la catégorie dans le classement. [cite:@jonathanschwabishTime2021] Si la valeur source est également à représenter, ce graphique peut se transformer en graphique en ruban, combinant les disposition du graphique en bosse avec celles du graphique de Sankey. [cite:@jonathanschwabishTime2021]

** Camembert
:PROPERTIES:
:en-name: Pie chart
:chart-goal: Partie d'un ensemble
:data-type-x:
:data-type-y:
:END:
Diagramme standard, difficile à lire. [cite:@alansmithLexiqueVisuel]
Limiter à 5 (4?) entrées maximum [cite:@mikeyiHowChooseRight2020]

Ce graphique doit être limité à l'illustration d'un état donnée. Il est important de garder à l'esprit que ce graphique ne donne qu'une représentation et n'est pas adapté à l'affichage de valeurs précises. [cite:@jonathanschwabishParttowhole2021]

Le camembert permet d'accentuer l'appartenance d'une partie individuelle à un ensemble homogène et complet. Il illustre parfaitement des fractions simples.[cite:@wilkeDirectoryVisualizations2019] Les quantités n'ont pas leurs place dans un camembert, ce sont les fractions (taux, pourcentages) qui y sont illustrés. Ainsi, l'ensemble des valeurs constituante sont strictement égale à 100% du total.[cite:@wilkeVisualizingAmounts2019] Il représente plus efficacement les parts dont les angles sont familiers aux lecteurs soit respectivement 90°, 180° et 240° pour les taux 25%, 50% et 75%.

Ce graphine n'est pas adapté à ces cas de figure :
- les parts sont de tailles similaires,[cite:@sosulskiGraphics2019]
- Il y a beaucoup de catégories à afficher pour atteindre l'objectif du message,
- il y a une comparaison entre deux graphiques à réaliser,[cite:@jonathanschwabishParttowhole2021]
- il y a un changement entre plusieurs états.[cite:@wilkeDirectoryVisualizations2019]

Il convient de :
- Arranger les parts par orgre de valeur croissant en commençant à '12h'. [cite:@jonathanschwabishParttowhole2021]
- Utiliser un espace vide entre chaque part pour les faire resortir, [cite:@sosulskiGraphics2019]
- Utiliser une palette de couleur de mise en évidence pour faire ressortir une seule part ou,
- Utiliser une palette de couleur pour faire resortir deux parts,
- Apposer les labels directement sur les parts au moyen d'étiquette. [cite:@sosulskiGraphics2019]

Les parties n'étant pas mises en avant peuvent être agrégée en une catégories "autres". Leurs informations ne servant pas à appuyer le message du graphique. [cite:@jonathanschwabishParttowhole2021]

Dans le cas ou une seule partie de l'ensemble est mise en avant, il est à considérer l'utilisation d'un [[marqueur]]. Le camembert n'apportant aucune information particulière à votre propos.

Il n'est pas encore clairement établis si la comparaison des valeurs est réalisé par la perception des angles ou par la perception des longueurs d'arcs des différentes parties.[cite:@jonathanschwabishParttowhole2021]

Ce diagramme possède un avantage majeur au regard des autres modes de représentation des parties d'un ensemble, il est très populaire et ainsi accessible à usager. [cite:@jonathanschwabishParttowhole2021] Il est également reconnu que les formes circulaires attirent l'intéret des utilisateurs.[cite:@jonathanschwabishParttowhole2021]

** Carte de fréquentation
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Excellente visualisation pour suivre la fréquence d'une activité. Favorise la quantité à la qualité (exemple : github). [cite:@alansmithLexiqueVisuel]

** Cascade
:PROPERTIES:
:en-name: Waterfall plot
:chart-goal: Déviation,Evolution
:data-type-x:
:data-type-y:
:END:
Affiche les gains et pertes entres deux états d'un système. [cite:@jonathanschwabishComparingCategories2021] Utilisé principalement pour les analyses financières. [cite:@alansmithLexiqueVisuel]

** Chandelier
:PROPERTIES:
:en-name: Candlestick
:chart-goal: Evolution,Déviation
:data-type-x:
:data-type-y:
:END:
Affiche des bilans quotidiens (eg. ouverture, fermeture, point haut, point bas). [cite:@alansmithLexiqueVisuel]
La couleur est utilisée pour représenter la direction de l'évolution de la valeur (augmente, descend).

Illustre les évolutions d'un stock sur une temporalité donnée. La ligne indique l'état le plus haut et l'état le plus bas de la journée. La barre indique l'état de l'ouverture et de la cloture de la période. [cite:@jonathanschwabishDistribution2021] Il convient d'utiliser une palette de couleur binaire pour contraster les périodes aux soldes positifs des périodes aux soldes négatifs.

** Chronologie circulaire
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Pour l'affichage des valeurs discrètes de taille variable à travers de multiples catégories. [cite:@alansmithLexiqueVisuel]

** Chronologie verticale
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Affiche le temps sur l'axe Y. Particulièrement adapté à l'affichage sur mobile. [cite:@alansmithLexiqueVisuel]

** Colonne vertébrale
:PROPERTIES:
:en-name: Spine chart
:chart-goal: Déviation
:data-type-x:
:data-type-y:
:END:
Utilisé pour afficher la quantité de réponses négatives et positives à une question. Le spine divise une valeure quantitative unique en deux ccomposants distinct contrasté par un déterminent binaire. [cite:@alansmithLexiqueVisuel] Utilisé pour afficher la quantité de réponses négatives et positives à une question.

** Coordonnées parallèles
:PROPERTIES:
:en-name:
:chart-goal: Ordre de grandeur
:data-type-x:
:data-type-y:
:END:
Montre en simultané la valeur et la relation de catégories hétérogènes pour plusieurs systèmes. [cite:@jonathanschwabishRelationship2021] Permet de valoriser la valeur. [cite:@alansmithLexiqueVisuel]

Pratique pour observer les schémas et relations entre les systèmes. [cite:@mikeyiHowChooseRight2020] Ce graphique est plus efficace pour explorer des jeux de données que pour les présenter à un audimat. [cite:@sosulskiGraphics2019]

Chaque axes de catégories peut avoir sa propre échelle. Cela représente mieux les valeurs de chaque catégorie mais cela implique également de bien labeliser les axes pour distinguer leurs échelles. [cite:@jonathanschwabishRelationship2021]

Afficher un grand nombre de jeux de données sur un même graphe risque de le rendre illisible. [cite:@jonathanschwabishRelationship2021] Dans ce cas il convient d'utiliser une palette de couleur de mise en évidence et de selectionner un ou deux jeux de données à mettre en avant.

Lors de l'exploration d'un jeu de donnée à travers une interface informatique, il convient de mettre en avant la ligne pointée par l'utilisateur et de labeliser chaque points de catégorie avec la valeur associé. [cite:@sosulskiGraphics2019]

** Corde
:PROPERTIES:
:en-name: Chord diagram
:chart-goal: Flux
:data-type-x:
:data-type-y:
:END:
Illustre les flux bidirectionnels et le gagnant net dans une matrice. [cite:@alansmithLexiqueVisuel]

Dans la mesure du possible, il convient de flécher le sens du flux.

Ce diagramme incite les utilisateurs à l'explorer plus en détail. [cite:@jonathanschwabishRelationship2021]

** Courbe cumulative
:PROPERTIES:
:en-name:
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Utilisé pour représenter une distribution inégale. L'axe des ordonnées est toujours la fréquence cumulative et l'axe des absisses est toujours une mesure. [cite:@alansmithLexiqueVisuel]

** Courbe de densité
:PROPERTIES:
:en-name:
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
La densité représente la probabilité de distribution des variables. [cite:@sosulskiGraphics2019] Pertinent lorsque le nombre de données est très grand, autrement il convient d'utiliser un histogramme. [cite:@wilkeVisualizingManyDistributions2019] En cas d'affichage de plusieurs courbe, utiliser  des remplissages transparents pour faciliter la distinctions. L'air de la courbe est usuellement égal à 1 et de ce fait, l'échelle de l'axe des ordonnées dépend de l'axe des absisses. [cite:@wilkeVisualizingManyDistributions2019]

** Donut
:PROPERTIES:
:en-name:
:chart-goal: Partie d'un ensemble
:data-type-x:
:data-type-y:
:END:
Dans un graphique en donut, les valeurs sont à comparer en fonction des longueurs d'arcs.

Comme le diagramme circulaire, le centre peut être utilisé pour afficher un total ou encore une icone. [cite:@alansmithLexiqueVisuel]

# avantage de l'iconographie ?

# avantage de l'estétique ?

Il est, autrement, en tout point similaire aux [[camembert]]

** Etats parallèles
:PROPERTIES:
:en-name:
:chart-goal: Flux
:data-type-x:
:data-type-y:
:END:
Montre les changements sur un flux entre un état et au moins un autre. Adapté au traçage d'un processus complexe. [cite:@alansmithLexiqueVisuel]
Cette représentation découpe un ensemble en quantité individuelles de plusieurs catégories. Les bandes sont tracées entre chaque catégories pour représenter leurs relations. La largeur des bandes indiquent la proportion des catégories correllées les unes aux autres. [cite:@wilkeVisualizingNestedProportions2019]
A utiliser à la place des mosaiques et treemaps lorsqu'il y a plus de deux variables de regroupement des données. [cite:@wilkeDirectoryVisualizations2019]

** Eventail
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Utilisé pour montrer l'incertitude des projections futures. [cite:@alansmithLexiqueVisuel]

** Frise de Priestley
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Parfait lorsque la date et la durée sont des éléments clés dans l'histoire de la donnée. [cite:@alansmithLexiqueVisuel]

** Haltères
:PROPERTIES:
:en-name:
:chart-goal: Classement
:data-type-x:
:data-type-y:
:END:
Utilisé pour comparer un minimum et un maximum de plusieurs catégories. [cite:@alansmithLexiqueVisuel] La relation entre le maximum et le minimum d'une catégorie est représenté par la barre reliant les deux valeurs. [cite:@mikeyiHowChooseRight2020]

Peut être utilisé pour illustrer le changement d'une valeur entre deux état données. Dans ce cas, il convient de flécher le sens du changement de l'état antérieur vers l'état final.

Dans ces deux cas de figures, les catégories doivent êtres ordonnées de la plus grande valeur à la plus petite.

Les haltères sont toujours affichés à l'horizontal.

** Histogramme
:PROPERTIES:
:en-name: Histogram
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Utilisé pour afficher la fréquence d'une variable simple regroupée en intervale de fréquence (agrégat).[cite:@sosulskiGraphics2019] Il affiche ainsi une distribution statistique de donnée. Il n'y a pas d'espace entre deux barres (ratio 1:0) ce qui permet de favoriser la forme de la distribution. [cite:@alansmithLexiqueVisuel]

La nature du graphique (barre) implique un calcul d'agrégat pour chaque barre. [cite:@wilkeVisualizingDistributionsHistograms2019] La largeur de l'agrégat est à évaluer par le concepteur au regard du niveau de détail souhaité.[cite:@wilkeVisualizingDistributionsHistograms2019]

L'histogramme n'est pas adapté aux cas suivant :
- l'affichage de l'ensemble des valeurs, pour cela il convient d'utiliser une [[courbe de densité]]. [cite:@wilkeVisualizingDistributionsHistograms2019]
- s'il y a peu de valeurs dans le jeu de données, [cite:@weissgerberBarLineGraphs2015] préférez l'utilisation d'une [[bande de valeur]].
- l'affichage de plusieurs distributions,[cite:@wilkeVisualizingDistributionsHistograms2019] utilisez une décomposition en [[matrice de graphique]].

L'utilisation d'un histogramme permet d'identifier des schémas de distributions tels que : [cite:@jonathanschwabishDistribution2021]
- *Incliné à gauche :* les données sont majoritairement sur la gauche du graphique
- *Incliné à droite :* les données sont majoritairement sur la droite du graphique
- *Bimodale :* lorsque deux pics de valeurs sont constatables
- *Multimodale :* lorsque plus de deux pics de valeurs sont constatables
- *Symétrique :* lorsqu'il y a un nombre approximativement égal de valeurs de chaque coté d'une valeur centrale
- *Uniforme :* lorsque toutes les valeurs sont distribuées de façon globalement homogène

** Horizon
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Permet de vérifier un équilibre entre deux borne par rapport à une base. [cite:@alansmithLexiqueVisuel]  Utilisé pour suivre l'évolution d'une variable dans le temps et devant respecter un écart-type (eg. tension à 230V +/- 5%). L'information la plus importante est le dépassement de l'écart-type. Pour correctement mettre en évidence ces phénomènes, il est recommendé d'utiliser une palette de couleur de

** Jauge
:PROPERTIES:
:en-name: Gauge
:chart-goal: Indicateur
:data-type-x:
:data-type-y:
:END:
Les jauges sont des représentations familières et facile à lire. [cite:@jonathanschwabishComparingCategories2021] En ce sens, elles sont pertinente pour afficher des données. Cependant, il convient de s'intéresser particulièrement à leurs représentation métaphorique. Les graphiques en jauge étant un =skeumorphisme=, leurs utilisation est probablement plus pertinente pour l'affichage d'information pour lesquelles elles sont utilisées dans le monde physique.

Cela concerne par exemple :
- L'affichage d'une vitesse instantanée,
- L'affichage d'une pression instantanée et par extension,
- L'affichage d'un niveau dans un réservoir.

Pour tout autre usage, et considérant la difficulté humaine d'interprétation d'une valeur en comparant des angles ainsi que le manque d'options pertinentes pour ajouter des informations qualitatives sur les jauges, il convient d'utiliser un graphique en [[Tiret]].

** Ligne
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Inventé par Playfair en 1786 [cite:@sosulskiBecomingVisual2019]
Représentation graphique standard et famillière pour la représentation des séries temporelles. [cite:@alansmithLexiqueVisuel,@Schwabish2021p86]

Les lignes relient chaque point de mesure. Pour de grands jeux de données, il convient d'utiliser une ligne lissée sur l'ensemble du graphique plutot qu'une ligne brisée par chaque point de donnée. [cite:@wilkeDirectoryVisualizations2019]

La base des ordonnées doit être égale ou inférieure à la plus faible valeur affichée. [cite:@Wong2010]

Il n'existe pas de rêgle stricte quand à la limite de séries affichables sur un graphique.[cite:@jonathanschwabishTime2021] Il convient de s'intéresser à la perception du lecteur recherché par le concepteur pour arbitrer les choix : [cite:@jonathanschwabishTime2021]
- En cas d'impression, limiter le nombre de lignes simultanées à 4 au maximum, [cite:@Wong2010]
- Si l'interraction est possible avec le graphique, il est possible de tracer toutes les lignes dans un même graphique à condition d'utiliser un système de mise en évidence,[cite:@jonathanschwabishTime2021]
- Ces cas échouant, séparez les lignes et tracez une [[matrice de graphique]].

Ne pas utiliser ce graphique pour essayer d'illustrer une différence entre deux courbes. [cite:@jonathanschwabishTime2021]

Les axes doivent être labelisé (obligatoirement le titre de la série, optionnellement la valeur finale) directement en fin de ligne, à droite du graphique. [cite:@andreaskrauseBestPracticesData2024;@sosulskiGraphics2019]

Il est possible de mettre en évidence un point spécifique en utilisant un symbole (de préférence un cercle plein) et en y apposant une étiquette affichant \(f(x)=y\).

La distinction des séries est plus efficace en utilisant des teintes différentes. Dans ce cas, il convient également d'utiliser des tons différents pour assurer le maintiens des distinctions si le graphique est imprimé en nuance de gris. [cite:@stephenfewComponentlevelGraphDesign2012]
Il convient également de n'utiliser que des lignes continues pour les tracés. [cite:@stephenfewComponentlevelGraphDesign2012]
L'utilisation de symboles comme éléments différenciants entre les séries n'est pas pertinent. [cite:@stephenfewComponentlevelGraphDesign2012]

** Ligne de crête
:PROPERTIES:
:en-name: Ridgeline
:chart-goal: Comparaison
:data-type-x:
:data-type-y:
:END:
Ce graphique représente des courbes de densité séparées par un offset et est utilisé pour comparer la distribution d'une vrariable entre des catégories. [cite:@wilkeVisualizingManyDistributions2019] Parfait lorsque les schémas de distributions sont bien distincts entre les groupes. [cite:@mikeyiHowChooseRight2020] Cela évite que les courbes de densités des catégories s'entrevêchent.[cite:@jonathanschwabishDistribution2021]

Ce graphique se met très bien à l'échelle de grands jeux de données. [cite:@wilkeVisualizingManyDistributions2019]

Il est adapté à :
- la comparaison des changements de distributions à travers le temps [cite:@wilkeDirectoryVisualizations2019] associé à un gradiant de couleur pour diriger le regard vers la distribution la plus récente, [cite:@jonathanschwabishDistribution2021]
- la comparaison des évolutions de deux tendances à travers le temps. [cite:@wilkeVisualizingManyDistributions2019] associé à une palette de couleur binaire.

L'axe des absysses affiche la valeur de réponse et l'axe des ordonnées affiche les catégories. [cite:@wilkeVisualizingManyDistributions2019]

Il convient de classer les catégories suivant un ordre logique. [cite:@jonathanschwabishDistribution2021] Voir (insérer renvois ici vers l'explication de la logique de classement de catégories)

Il est possible d'afficher les barres d'erreurs dans les lignes de crêtes. Ce mode de représentation s'appel un "demi-oeil". [cite:@wilkeVisualizingUncertainty2019]

Il est possible d'afficher les nuages de points dont l'estimation de la courbe de densité est issue. Ceux-ci sont affichés en dessous des courbes de densité. Cette forme de représentation est appelé "Nuage de pluie". (ref: Micah Allan ou Schwabish2021p212) Cette représentation offre à la fois une représentation générique et une visualisation précise des données. [cite:@jonathanschwabishDistribution2021] Bien que cette représentation soit très efficace, elle n'est pas très répendue. [cite:@jonathanschwabishDistribution2021] Il faut être vigilent à bien expliquer son fonctionnement lors de son utilisation dans un rapport. Dans le cas d'un nuage de pluie, il faut faire attention à ce que les points de données n'entre pas en surimposition avec les courbes de densitées tracées en dessous.

** Lollipop
:PROPERTIES:
:en-name:
:chart-goal: Classement
:data-type-x:
:data-type-y:
:END:
Utilisé pour afficher la position dans une liste ordonnée lorsque l'affichage de la valeur est moins important que la position. [cite:@alansmithLexiqueVisuel] Egalement très efficace comparé aux barres hordonnées lorsqu'il y a un grand nombre de catégorie dans le classement. [cite:@mikeyiHowChooseRight2020]  Si une ligne connecte le point de la valeur à laxe des ordonnées, l'axe des absisse doit commencer à 0, autrement cela n'est pas obligatoire.

** Marqueur
:PROPERTIES:
:en-name: Big number
:chart-goal: Indicateur
:data-type-x:
:data-type-y:
:END:
Affiche une valeur simple, plus pertinent lorsqu'associé à une tendance sur une période donnée. [cite:@mikeyiHowChooseRight2020]

** Marimeko
:PROPERTIES:
:en-name:
:chart-goal: Ordre de grandeur
:data-type-x:
:data-type-y:
:END:
Visualisation de la taille et des proportions d'un ensemble homogène de données. [cite:@alansmithLexiqueVisuel]
Exemple : répartition des parts de marché de 3 entreprises sur un axe et taux dans 3 catégories de marché pour chacune

La couleur peut être utilisée pour mettre en évidence une valeur. [cite:@jonathanschwabishComparingCategories2021] Attention au biais de correlation lorsque ce graphique est utilisé pour représenter plusieurs variables. [cite:@jonathanschwabishComparingCategories2021]

** Matrice de bulle
:PROPERTIES:
:en-name:
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:
Ce graphique est une version aggrégée du nuage de bulle et le la matrice de température.

Il simplifie la visualisation des relations entre un couple de variable. A réserver pour un usage d'exploration de donées. [cite:@sosulskiGraphics2019] La taille des bules représente la force de la corrélation. Cette force est la représentation du coefficient de Pearson. [cite:@jonathanschwabishRelationship2021]

La couleur peut être utilisée pour distinguer les catégories (à vérifier). Elle peut être également utilisée comme double encodage de la correlation (à vérifier).

Le tableur associée est une matrice de correlation organisant les valeurs de coefficient de Pearson.

** Matrice de graphique
:PROPERTIES:
:en-name: Small multiples
:data-goal: Comparaison
:data-type-x:
:data-type-y:
:END:

Origine
Est utilisé pour comparer de multiples graphiques homogènes organisées en matrices. Chaque entité affiche le graphique d'une catégorie. Les graphiques sont tous à la même échelle. [cite:@sosulskiGraphics2019]

Conseils : Limitez les détails dans chacun des graphique. [cite:@sosulskiGraphics2019] Regroupez les axes pour n'afficher qu'un seul axe Y par ligne et un seul axe X par colonne.

** Matrice de température
:PROPERTIES:
:en-name: Heatmap
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:
Représentation graphique d'une table de valeur homogène. [cite:@sosulskiGraphics2019]
Intéressante pour afficher une tendance lorsqu'un très grand nombre d'information est impliqué.

En utilisant une palette de couleur séquentielle, un lecteur aura tendance à considérer une couleur sombre comme une valeur haute. En utilisant une palette de couleur divergente (eg. basée sur la température de la couleur), ce phénomène s'estompe.

L'organisation des catégories changeant la forme de la matrice de température, il convient de retenir une organisation par valeur croissante ou décroissante à une colonne donnée. Il convient de signaler cette configuration au lecteur. [cite:@wilkeVisualizingAmounts2019]

** Mini-graphe
:PROPERTIES:
:en-name: Sparkline
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Affiche la tendance d'évolution d'une variable ou d'une catégorie. Est généralement intégré dans un tableur. Un mini-graphe ne possède pas d'axes ni d'autres détails et est composé uniquement d'une courbe et d'un point indiquant la dernière valeur du jeu de donnée. [cite:@sosulskiGraphics2019] Cette représentation est très macroscopique et vise à succiter un sentiment plutot que d'exposer une valeur précise. [cite:@jonathanschwabishDistribution2021]

Un mini-graphe ne possède pas d'axes ni d'autres détails.

** Nuage de bulle
:PROPERTIES:
:en-name:
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:
Il s'agit d'un nuage de point dont la taille des bules est utilisé pour représenter une troisieme valeur quantitative. [cite:@alansmithLexiqueVisuel]

** Nuage de mots
:PROPERTIES:
:en-name:
:chart-goal: Ordre de grandeur
:data-type-x:
:data-type-y:
:END:
Affiche des nuages de mots organisés en groupes sémantiques. La taille des mots indique leur fréquence d'utilisation dans le corpus étudié. La couleur des groupes peut représenter un choix de données qualitative (catégorisation). [cite:@sosulskiGraphics2019] Cette visualisation est une méthode d'exploration de texte utile pour réaliser une synthèse macroscopique.
Il convient de filtrer les mots vides dit "stopwords" pour nettoyer la composition des nuages. [cite:@jonathanschwabishQualitative2021] Des listes de mots vides peuvent être trouvées à l'adresse <https://github.com/stopwords-iso/>.

** Nuage de point
:PROPERTIES:
:en-name:
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:

#+ATTR_LATEX: :float wrap :width 1.2cm :placement {l}{0.8cm}
[[./img/icon-scatterplot.pdf]]

Représente la relation entres deux variables continues. [cite:@alansmithLexiqueVisuel]
La couleur est la meilleure façon de distinguer les catégories.[cite:@stephenfewComponentlevelGraphDesign2012] Pour cela, utilisez la pallette catégorique ([[fig:Pal-c]])

Dans un maximum de 4 catégories de données, il est possible d'utiliser un double encodage combinant une forme et une couleur.[cite:@andreaskrauseBestPracticesData2024]

les formes recommandées sont :

#+caption: Formes des points de données
#+name: fig:formes
#+attr_latex: :width 3.2cm :placement [H]
[[./img/formes.pdf]]


Si des milliers de point de données sont à afficher, il est préférable d'utiliser soit :
- des cercles ouverts,
- des petits cercles,[cite:@stephenfewComponentlevelGraphDesign2012]
- des cercles avec une transparence.[cite:@stephenfewComponentlevelGraphDesign2012]

  Cela permet de limiter le masquage des points de données par surimposition. [cite:@andreaskrauseBestPracticesData2024]

** Nuage de point connecté
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Montre l'évolution des données pour deux variables pertinentes si le modèle de progression est clair. [cite:@alansmithLexiqueVisuel]

Pour souligner la direction de l'évolution entre deux points il est possible de :
- Flécher la direction de l'évolution entre deux points si les points sont bien espacés et qu'un seul jeu de donnée est affiché, [cite:@jonathanschwabishComparingCategories2021]
- Utiliser un gradiant de couleur du plus clair vers le plus foncé.

Ce graphique sers à synthétiser des variations de valeurs, il est préférable de l'utiliser pour afficher des jeux de données dont la variation n'est pas mesurée régulièrement pour éviter d'avoir trop de points à relier et donc d'éviter de créer un graphique trop encombré. [cite:@jonathanschwabishComparingCategories2021]

** Pareto
:PROPERTIES:
:en-name:
:chart-goal: Correlation
:data-type-x:
:data-type-y:
:END:
Ce type de graphique montre la relation entre les valeurs quantitatives de catégories organisées en colonne ordonnée et la valeur cumulée affichée en ligne brisée. Le premier point de la ligne vérifiant \(\tau\geq80\%Total\) est affichée. La zone précédent ce point est mise en évidence.
Est utilisé pour illustrer les éléments important dans un système qualité.

** Pente
:PROPERTIES:
:en-name:
:chart-goal: Classement
:data-type-x:
:data-type-y:
:END:
Affiche la variation des valeurs ou ratios des catégories entre deux états donnés. [cite:@alansmithLexiqueVisuel]

** Pictographe
:PROPERTIES:
:en-name:
:chart-goal: Ordre de grandeur
:data-type-x:
:data-type-y:
:END:
Utilisation hautement contextuelle limiter strictement à l'affichage d'entiers naturels. [cite:@alansmithLexiqueVisuel]
Les pictographes peuvent augmenter significativement la précision d'acquisition d'un écart de ratio ainsi que la rapidité de la visualisation d'un minimum ou d'un maximum entre des catégories. [cite:@tranDiscoveringAccessibleData2024] A la manière des symboles groupées, si la transmission de valeurs précise est importante, il convient d'utiliser un graphique en barre ordonnée à la place. [cite:@tranDiscoveringAccessibleData2024]

** Polygone de fréquence
:PROPERTIES:
:en-name:
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Utilisé pour afficher simultanément plusieurs distributions de données. Fonctionne comme un histogramme. Chaque agrégat est représenté par un point et ils sont reliés entres eux par un segment droit. Pour faciliter la lécture, il convient de limiter le nombre de distributions affichées à 4 [cite:@alansmithLexiqueVisuel] ce qui correspondant notamment au nombre de symboles aisément discriminables.

** Quadrillage
:PROPERTIES:
:en-name:
:chart-goal: Partie d'un ensemble
:data-type-x:
:data-type-y:
:END:
Adapté à l'affichage des informations en pourcentages. Fonctionne mieux avec des entiers naturels. [cite:@alansmithLexiqueVisuel] Généralement en grille de 10 x 10 carrés (pour un total de 100). Chaque carré représente 1% d'un tout. Les carrés sont colorés sur la base de la taille d'une catégorie dans un groupe. [cite:@mikeyiHowChooseRight2020]

** Radar
:PROPERTIES:
:en-name:
:chart-goal: Ordre de grandeur
:data-type-x:
:data-type-y:
:END:
Représentation compacte de la valeur de variables hétérogènes pour un seul système. [cite:@alansmithLexiqueVisuel] Les radards sont utilisés pour identifier les variables ayant des valeurs similaires et les exceptions. [cite:@sosulskiGraphics2019]

La représentation des valeurs se fait à travers la forme globale du polygonne. Il convient de coloriser l'interrieur de celui-ci pour bien faire ressortir sa forme. [cite:@jonathanschwabishRelationship2021]

Utiliser une disposition en small-multiples plutot que de surimposer plusieurs polygones de valeurs. [cite:@jonathanschwabishRelationship2021]

La représentation des variables est fortement correlé à la forme du polygone plutot qu'aux valeurs des sommets. [cite:@sosulskiGraphics2019] De ce fait, pour améliorer la forme du polygonne et offrir une représentation avec le moins de distortions possibles, il convient d'homogénéiser les échelles des axes.

** Réseau
:PROPERTIES:
:en-name: Network
:chart-goal: Flux
:data-type-x:
:data-type-y:
:END:
Utilisé pour montrer la force et l'interconnectivité des relations de types différents. [cite:@alansmithLexiqueVisuel] La position des nœuds n’a pas de fonction logique. Elle vise à rendre le diagramme le plus lisible possible. [cite:@mikeyiHowChooseRight2020]

** Ruisseau
:PROPERTIES:
:en-name: Streamgraph
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:

Vérifier la méthafore liée au nom

A privilégier lorsque la visualisation des changements en proportions au fil du temps est plus importante que les valeurs individuelles. [cite:@alansmithLexiqueVisuel]

** Sankey
:PROPERTIES:
:en-name:
:chart-goal: Flux
:data-type-x:
:data-type-y:
:END:
Créé par : Matthew Henry Phineas Riall Sankey (1898)
L'épaisseur représente la part d'un évènement. Chaque flèche représente l'entrée ou la sortie d'élément sur le système étudié. [cite:@mikeyiHowChooseRight2020]

Les changements sont liés à une évolution temporelle et à l'association de catégories. La force de ce graphique est qu'aucun de ces deux aspect ne pévaut sur l'autre. [cite:@jonathanschwabishComparingCategories2021]

Très utile pour représenter les flux entre des catégories ou entre des états. [cite:@jonathanschwabishComparingCategories2021]

Il convient néanmoins de limiter le nombre de catégorie  affiché pour maintenir un bon niveau de lisibilité. [cite:@jonathanschwabishComparingCategories2021]

** Sismographe
:PROPERTIES:
:en-name:
:chart-goal: Evolution
:data-type-x:
:data-type-y:
:END:
Pour montrer des séries à grandes variation dans les données. [cite:@alansmithLexiqueVisuel]

** Symbole groupé
:PROPERTIES:
:en-name:
:chart-goal: Ordre de grandeur
:data-type-x:
:data-type-y:
:END:
Utile lorsqu'il est utile de compter ou de mettre en évidence des éléments individuels organisés en barre ou en colonne. [cite:@alansmithLexiqueVisuel] Cependant, ce type de graphique n'est pas efficace dans cette action car il incite le lecteur à compter chaque point, ce qui peut s'avérer décourageant. [cite:@stephenfewSillyGraphsThat2012] Un certain usage peut être imaginé à des fins décoratives visant à illustrer un élément déjà explicité dans un texte. Un graphique en barre ordonné est à privilégier aux symboles groupés.

** Tiret
:PROPERTIES:
:en-name: Bullet point
:chart-goal: Indicateur
:data-type-x:
:data-type-y:
:END:
selont Schwabish : inventé par Few

La valeur actuelle mesurée ou calculée est observée au moyen d'une barre horizontale constrastant avec l'arrière plan. [cite:@jonathanschwabishComparingCategories2021]
La valeur cible est représenté par une ligne verticale. [cite:@alansmithLexiqueVisuel]
L'arrière plan expose 3 zones dites qualitative et associées à des notions de performance (eg. inférieur, moyen, bon). [cite:@sosulskiGraphics2019]

Editer une série de tirets permet d'exposer au lecteur diverses comparaisons tout en restant compacte. [cite:@jonathanschwabishComparingCategories2021]

Cette représentation est notamment pertinente lors de la réalisation d'un benchmark. [cite:@mikeyiHowChooseRight2020]
# Définir benchmark

** Tunnel
:PROPERTIES:
:en-name: Funnel
:chart-goal: Flux
:data-type-x:
:data-type-y:
:END:
Utilisé pour suivre l'engagement d'une population (taille) à chaque étape d'un processus (barre). [cite:@mikeyiHowChooseRight2020]

** Treemap
:PROPERTIES:
:en-name: Treemap
:chart-goal: Partie d'un ensemble
:data-type-x:
:data-type-y:
:END:
Utilisé pour les relations hiérarchiques d'une partie vers l'ensemble. Difficile à lire s'il y a trop d'éléments affichés. [cite:@alansmithLexiqueVisuel]
Le découpage des boites n'a pas besoin d'être ordonné, il peut y avoir plus de 2 niveaux de hiérarchie. [cite:@mikeyiHowChooseRight2020]

** Valeur lettrée
:PROPERTIES:
:en-name: Letter value
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Représente chaque découpage statistique (\(x\sigma\)) par une boite distincte. Convient en remplacement des boites à moustache lorsqu'il y a un très grand nombre de données disponibles. Permet de faire des estimations fiables. [cite:@hofmannLettervaluePlotsBoxplots2017;@mikeyiHowChooseRight2020 ]

** Violon
:PROPERTIES:
:en-name:
:chart-goal: Distribution
:data-type-x:
:data-type-y:
:END:
Représente fidèlement les distributions d'un très grand nombre de données. [cite:@alansmithLexiqueVisuel] Utilisé pour faire des comparaisons entre des catégories. [cite:@mikeyiHowChooseRight2020]  Très pertinent pour représenter les distributions bimodales. [cite:@wilkeVisualizingManyDistributions2019] Le tracé du demi-violon est identique au tracé d'une courbe de densité. Celui-ci commence à la valeur la plus petite et termine à la valeur la plus grande.

** Voronoi
:PROPERTIES:
:en-name:
:chart-goal: Partie d'un ensemble
:data-type-x:
:data-type-y:
:END:
Semblable à un diagramme de bulle mais transformées en zones dont l'ensemble des points de chacune est plus proche du centre de sa zone que de tout autre centroïde. [cite:@alansmithLexiqueVisuel]

Il est très pertinent pour illustrer les parties d'un ensemble lorsque de nombreuses sous-catégories sont à afficher. [cite:@jonathanschwabishParttowhole2021] En ce sens, il est préféré aux camenberts.

* Etudes futures
Des études complémentaires pourraient être menées sur les sujets suivants :
- La conception de librairies de graphiques accessibles et fonctionnant aussi bien dans un usage web que dans les PDF,

* Evolution
|       Date | Changements           |
|------------+-----------------------|
| 2025-02-10 | Rédaction du document |

* Glossaire
** Vocabulaire technique 
- Big data :: Désigne les ressources d’informations dont les caractéristiques en termes de volume, de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques particulières pour créer de la valeur et qui dépassent en général les capacités d'une seule et unique machine. [cite:https://fr.wikipedia.org/wiki/Big_data]
- Jumeau numérique :: Modèle numérique qui reconstitue fidèlement un objet, une opération ou un système tel qu'utilisé (ou maintenu/exploité). [cite:https://fr.wikipedia.org/wiki/Jumeau_num%C3%A9rique]
- Médium :: Moyen par lequel est transmise une information. [cite:https://fr.wikipedia.org/wiki/M%C3%A9dium]
- Réalité étendue :: Mise en œuvre de technologies de réalité augmentée (AR), de réalité virtuelle (VR) et de réalité mixte (MR) dont l'objectif est de fusionner ou de refléter le monde physique avec un monde numérique qui peut interagir avec lui. [cite:https://fr.wikipedia.org/wiki/R%C3%A9alit%C3%A9_%C3%A9tendue]
- Retours haptiques :: Technologie utilisant les vibrations pour stimuler le toucher. [cite:https://fr.wikipedia.org/wiki/Vibration_(jeu_vid%C3%A9o)#Retour_haptique]
- Skeumorphisme :: Elément de design dont la forme n'est pas directement liée à la fonction, mais qui reproduit de manière ornementale un élément qui était nécessaire dans l'objet d'origine. [cite:https://fr.wikipedia.org/wiki/Skeuomorphisme]
- Sonification :: Représentation et émission de données sous forme de signaux acoustiques non verbaux aux fins de la transmission ou de la perception d’information. [cite:https://fr.wikipedia.org/wiki/Sonification] 

** Troubles neurodivergents
- Autisme :: Troubles caractérisé par des difficultés dans les interactions sociales et la communication, ainsi que par des comportements et intérêts à caractère restreint, répétitif et stéréotypé. [cite:https://fr.wikipedia.org/wiki/Autisme]
- Dyscalculie :: Trouble sévère dans les apprentissages numériques, sans atteinte organique, sans troubles envahissants du développement et sans déficience mentale et engendrant notamment des difficultés en mathématiques. [cite:https://fr.wikipedia.org/wiki/Dyscalculie]
- Dyslexie :: Trouble de la lecture et de l'écriture spécifique et durable [...] qui peut se traduire à divers degrés par des difficultés à épeler les mots, lire vite, écrire, lire à voix haute ou bien comprendre ce qui est lu. [cite:https://fr.wikipedia.org/wiki/Dyslexie]
- Dysorthographie :: Dysfonctionnement de l’écriture dû à un trouble d'apprentissage persistant de l’acquisition et de la maîtrise de l’orthographe et, pouvant se charactériser par des erreurs orthographiques, de conjugaison, de grammaire et d’analyse, des erreurs visuelles, etc. [cite:https://fr.wikipedia.org/wiki/Dysorthographie]
- Epilepsie :: Prédisposition cérébrale à engendrer des "crises" épileptiques dites "non provoquées", c'est-à-dire spontanées, non expliquées par un facteur causal immédiat. [cite:https://fr.wikipedia.org/wiki/%C3%89pilepsie]
- TDA/H :: Trouble provoquant trois types de symptômes pouvant se manifester seuls ou combinés : des difficultés d'attention et son contrôle, des symptômes d'hyperactivité et d'hyperkinésie. [cite:https://fr.wikipedia.org/wiki/Trouble_du_d%C3%A9ficit_de_l%27attention_avec_ou_sans_hyperactivit%C3%A9]

** Troubles de la vision [cite:https://fr.wikipedia.org/wiki/Daltonisme]
- Achromatopsie :: Absence totale de vision des couleurs.
- Deutéranopie :: Incapacité à différencier le rouge du vert.
- Deutéranomalie :: Sensibilité au vert réduite avec une tendance à le confondre avec le jaune.
- Protanopie :: Absence totale de la perception du rouge.
- Protanomalie :: Sensibilité au rouge réduite avec une tendance à le confondre avec le vert.
- Tritanopie :: Absence totale de la perception du bleu.
- Tritanomalie :: Sensibilité au bleu réduite avec une tendance à le confondre avec le vert ou le jaune.
  
* Acronymes
- BIM :: Building Information Modeling
- BIS :: Building Information System
- BOS :: Building Operating System
- IoT :: Internet of Things
- TDA/H :: Trouble du déficit de l'attention avec ou sans hyperactivité
- VDC :: Virtual Design and Construction
  
* Références
#+print_bibliography: :heading none

#+LaTeX_HEADER: \end{multicols}

