#+title: Méthode de sélection et de configuration des représentations graphiques des corpus d'informations
#+bibliography: "data-viz.bib"
#+author: Cyprien PIERRE
#+language: fr
#+Abstract: Add abstract here
#+keywords: Visualisation de données, Méthode de sélection, Charte graphique, Bonnes pratiques


* Introduction
La visualization de donnée est une discipline ancienne à la littérature riche et précise. Cependant, il n'existe, à ce jour pas de synthèse opérationnelle ni de méthode harmonisée dans la conception des représentations graphiques des informations. Ce rapport vise à fournir un point de départ cohérent à de futurs travaux en représentation visuelle d'informations. Il est basé sur une revue de littérature rigoureuse et les recommendations qu'il porte sont issues des lectures réalisées. Une tentative est réalisée d'objectiver les usages des diverses représentations.

L'origine de ces travaux prend place dans un besoin grandissant de solution de visualization d'information dans le secteur de la construction. Les technologies de Big Data, BIM, VDC et les disciplines de la science des données ont fortement pénétré ce secteur sur l'ensemble du cycle de vie des ouvrages. [cite:@asiauniversitytaichungtaiwanResearchApplicationFunctiontechnologyaesthetics2020] L'utilisation renforcée de l'IoT, l'émèrgence des BIS et BOS et l'intégration des solutions d'intelligences artificielles renforcent d'autant plus la nécessité pour ce secteur de se doter de moyens robuste en exploration et en communication des informations.

Le secteur de la construction est historiquement peu digitalisé en comparaison avec les autres industries. Pour adresser ce retard, il est important de publier des études opérationnelle claires et industrialisables dont chaque acteur de l'industrie de la construction puisse bénéficier immédiatement. Ce rapport s'inscrit dans cette démarche.

Il existe de multiples manières d'interargir avec un graphique. [cite:@schwabish1CenteringAccessibility2022;@frankelavsky2RightTools2022;]

Ce rapport aborde :
- L'exploration visuelle
- La lecture des tables
- L'écoute des descriptions
- La sonification des données
- L'interractivité avec les commandes de clavier
Ces éléments impliquent la mise en oeuvre de solution programmatique d'accessibilité pouvant intégrer une logique globale de préparation de graphiques numériques.

Ce rapport n'aborde pas :
- L'exploration en réalité mixte
- Les retours haptiques
- L'emploi d'écran à relief (braille)
Ces éléments nécessitant l'emploi de matériels spécifiques.

* Démarche
La conduite de cette revue s'est déroulé de la manière suivante :
Nous avons commencé par dresser un panorama des types de graphiques existant en nous appuyant sur les travaux de "From Data to Viz"[cite:@yanholtzDataViz2018], "The Graphic Continuum"[cite:@jonathanschwabishGraphicContinuum2014], "Lexique Visuel"[cite:@alansmithLexiqueVisuel], "Insights for ArcGis"[cite:@lindabealeInsightsArcGIS2017].
Cette première action nous a permis de pré-catégoriser les graphiques selon leurs utilisation.

Ensuite, nous avons étudié les livres de divers auteurs et en avons tirés un ensemble de rêgles générales quant à la préparation des graphiques. Cela concerne les aspects visuels (couleurs, polices...), des conseils sur la pertinence dans le choix des types graphiques suivant les objectifs attendus, quelques éléments d'accessibilités et des retours d'expériences. Sur cette base, nous avons affiné la catégorisation préétablies et commencé à regrouper les recommendations.

Pour compléter les dispositions propres à l'accessibilité, nous avons étudié le rapport "Centering accessibility in data visualization"[cite:@schwabishCenteringAccessibilityData2022]. Nous en avons tiré un apperçu global des approches possibles pour améliorer l'accessibilité des graphiques ainsi que de nombreux conseils et bonnes pratiques.

En parallele, nous avons étudié diverses chartes de publications issues de divers médias et institutions. Ces lectures nous ont permis de nourrir les reccommendations en matière de conception visuelle des graphiques ainsi que de dresser une liste d'éléments standardisables et d'autres pouvant être laisser libre de personnalisation avec quelques conseils.

Pour finir, nous avons étudié les articles scientifiques publiés sur ces sujets avec une profondeur de recherche à 5 ans. Ce choix de profondeur résulte d'une évolution conséquente depuis le début de la décenie des sciences de l'information. Cetains papiers étudiés sont plus anciens mais ont été très régulièrement cités par d'autres publications et nous avons choisis de les considérer. De cette étape, nous avons affiné les recommendations en identifiant les résultats d'expérimentations.

* Sémantique

* Eléments généraux
** Polices
Le choix d'une police de texte a de multiples impacts sur la perception des graphiques. Il convient de selectionner une police accessible et de préférence sans sérif pour un usage informatique (Arial, Calibri, Source Sans Pro, Verdana...).[cite:@andreaskrauseBestPracticesData2024] Les polices avec serif peuvent être considérés pour la production d'éléments imprimés. Il n'y a pas de consensus clair sur l'impact des sérifs sur l'accessibilité des polices.[cite:@stephenfew8TableDesign2012] Il n'y a pas non plus de consensus clair sur l'efficacité des polices conçues pour adresser des problématiques d'accessibilités telles que la dyslexie. Il convient d'utiliser une police utilisant une hauteur fixe pour les chiffres.[cite:@stephenfew8TableDesign2012]

Il est conseillé de restreindre l'utilisation de l'italique car les textes affichés de la sorte sont plus difficiles à lire. Il est égalemenbt conseiller de limiter l'utilisation de la graisse et du soulignement à des cas spécifiques pour ne pas surcharger les présentations.

La taille de la police joue un role majeur dans l'accessibilité du texte. Il est recommendé d'utiliser une hauteur de police de 12 points.[cite:@andreaskrauseBestPracticesData2024] Le nombre de tailles et de type de police doit être limité en nombre.[cite:@andreaskrauseBestPracticesData2024]

Certaines polices peuvent être utilisés pour projeter des icones (NerdFont, StateFace...).[cite:@jonathanschwabish10Qualitative2021] L'intérêt des icones est discuté plus tard dans ce rapport.

Il est important de prévoir le chargement de toutes polices non standard (eg. Source Sans Pro, NerdFont...) dans l'interface utilisateur si celles-ci sont utilisées puisqu'elles ne sont probablement pas installées dans le système d'exploitation de l'utilisateur. Prévoir leurs chargement vise à assurer la bonne expérience des utilisateurs.

** Tables
Une table ou tableur permet d'exposer des données brutes organisées en lignes ou en colonnes.

Sauf mention contraire, les recommendations sur les tables sont issues du livre "Show me the numbers" de Stephen Few.[cite:@stephenfew8TableDesign2012] L'auteur y rentre très en détails sur chaque point de paramétrage. Il y indique notamment les orientations en matière de construction de tableur lorsqu'il s'agit du choix premier d'affichage de données. Ce rapport s'intéresse à la conception de graphique. Dans ce cadre, les tableurs sont des éléments complémentaires pouvant être affichés par l'utilisateur pour explorer plus précisement les données préalablement affichées.

Pour composer une table de donnée lisible, il est recommendé de :
- Séparer les entrées avec un espace vide,
  - Lorsque les données sont présentées en colonnes, l'espace entre deux colonnes doit être plus grand qu'entre deux lignes,
  - Lorsque les données sont présentées en ligne, l'espace entre deux ligne doit être plus grand qu'entre deux colonnes,
  - Insérer une ligne vide toutes les 5 lignes pour faciliter le balayage visuel [cite:@ISO 9241-125:2018]
- Utiliser une ligne horizontale pour séparer les entêtes de colonnes des données,
- Utiliser une ligne horizontale pour séparer les catégories lorsque les données sont triées par catégories,
  - Dans ce cas de figure, ne pas répéter le nom de la catégorie sur toutes les lignes,
  - Les noms des catégories doivent être dans la première colonne, les sous-catégorie dans la seconde colonne, etc. S'il y a plusieurs subdivisions, les noms des catégories doivent être apposées sur la même ligne,
  - Rappeler le nom de la catégorie en cas de changement de page,
  - Maintenir la structure du tableur sur toutes les catégories,
- Rappeler les titres des colones en cas de changement de page,
- Les catégories doivent être ordonnées suivant un ordre logique (eg. chronologique, alphabetique, par classement, etc.)
- Valeurs sommairisées
  - Utiliser une ligne verticale pour séparer les valeurs placées en colonne à droite de toutes les valeurs
  - Utiliser une ligne horizontale si ces valeurs sont placées en une ligne en bas du tableau,
  - Si ces valeurs sont le message important de votre tableur, il convient de les affichés imédiatement à droite des colonnes de catégories ou immédiatement en dessous des entêtes de colonnes, suivant la nature du sommaire.
- Ne pas effectuer de rotation sur un tableur, son orientation doit respecter celle du texte du document,
- Les produits d'un calcul doivent être affichés dans la colonne imédiatement à droite de la colonne source de données
- Uniformiser les aligmnements
  - Les titres des colonnes suivent les alignements des données
  - Aligner les chiffres à droite,
    - Homogénéiser les décimales (généralement 2 ou 3 décimales suffisent suivant le contexte),
    - Indiquer les valeurs négatives avec le symbole "moins" (-), ici la notion de valeur symbolique est importante. Certains choisissent d'identifier les valeurs négatives entre parenthèses, cependant il ne s'agit pas d'une représentation naturelle répendue pour une telle identification.
    - Séparer les digit d'un nombre par un espace tous les 3 charactères. Dans le cas de grands nombres, il convient de les arrondir à la précision utile (dixaine, centaine...). Par défaut, la précision affichée doit correspondre à celle de la source d'information.
    - Si une valeur numérique réfère à une information de catégorie elle doit être traitée comme un texte.
  - Aligner les textes à gauche,
  - Centrer les dates et utiliser une convention stricte d'écriture de ces données telles que "YYYY-MM-DD".[cite:@ISO 8601] La composition de la date doit être indiqué à l'utilisateur. Le choix du format doit respecter le niveau de précision associée à la mesure. Implicitement, le choix d'un formatage de plus haut niveau que la précision de la mesure induit une agrégation des valeurs.
  - Centrer les données dont la largeur de charactère est fixe

Si des valeurs spécifiques doivent être mises en avant, il est possible d'utiliser l'une ou l'autre de ces solutions :
- mettre le texte en gras,
- remplir la cellule d'une couleur.
Il est recommandé de limiter cette opération à un nombre réduit de valeur. Si cela n'est pas possible, il convient de sélectionner un autre mode de visualisation.

Des prescriptions spécifiques à la préparation de tableurs pour certains graphiques sont apportés le cas échéant dans la suite de ce rapport.

* Graphiques
** Marqueur #indicateur
Affiche une valeur simple, plus pertinent lorsqu'associé à une tendance sur une période donnée.

** Jauge #indicateur
Représentation métaphorique  la vitesse d'un système.

** Tiret #indicateur
Présentation d'une valeur mesurée ou calculée au regard d'une valeur cible et ... . Pertinent lors de la réalisation d'un benchmark.

** Barres divergentes #deviation

** Barres divergentes empilées #deviation
Utilisé pour illustrer les résultats d'enquêtes impliquant un sentiment. Les barres doivent être calculées en pourcentage et alignées à 100% comme pour une partie d'un ensemble. Les réponses sont affichées de façon ordonée et du plus négatif au plus positif. Il convient d'utiliser une palette de couleur divergente. Lors de la préparation d'une enquête impliquant des sentiment, il est conseiller de proposer un choix de valeur paires pour éviter les votes neutres sauf si la représentation de l'indiférence est une volontée de l'étude. De plus, *expliquer la limite de nombre de zones facile à visualiser* (max 6?)

** Spine #deviation
Utilisé pour afficher la quantité de réponses négatives et positives à une question. Le spine divise une valeure quantitative unique en deux ccomposants distinct contrasté par un déterminent binaire.Utilisé pour afficher la quantité de réponses négatives et positives à une question.

** Horizon #evolution
Permet de vérifier un équilibre entre deux borne par rapport à une base. Utilisé pour suivre l'évolution d'une variable dans le temps et devant respecter un écart-type (eg. tension à 230V +/- 5%). L'information la plus importante est le dépassement de l'écart-type. Pour correctement mettre en évidence ces phénomènes, il est recommendé d'utiliser une palette de couleur de

** Cascade #deviation #evolution
Affiche les gains et pertes entres deux états d'un système. [cite:@JSchwabish 2021 p130]

** Bougies #deviation #evolution
Illustre les évolutions d'un stock sur une temporalité donnée. La ligne indique l'état le plus haut et l'état le plus bas de la journée. La barre indique l'état de l'ouverture et de la cloture de la période.[cite:@JSchwabish 2021 p199] Il convient d'utiliser une palette de couleur binaire pour contraster les périodes aux soldes positifs des périodes aux soldes négatifs.

** Nuage de point #correlation
Représente la relation entres deux variables continues.
La couleur est utilisée pour distinguer les catégories.
Si des milliers de point de données sont à afficher, il est préférable d'utiliser soit :
- des cercles ouverts
- des petits cercles
- des cercles avec une transparence
  Cela permet de limiter le masquage des points de données par surimposition. [cite:@AKrause 2024 p12]

** Nuage de bulle #correlation
Il s'agit d'un nuage de point dont la taille des bules est utilisé pour représenter la valeur quantitative.

** Matrice de température #correlation
Représentation graphique d'une table de valeur homogène. [cite:@Sosulski 2019 p52]
Intéressante pour afficher une tendance lorsqu'un très grand nombre d'information est impliqué.

En utilisant une palette de couleur séquentielle, un lecteur aura tendance à considérer une couleur sombre comme une valeur haute. En utilisant une palette de couleur divergente (eg. basée sur la température de la couleur), ce phénomène s'estompe.

L'organisation des catégories changeant la forme de la matrice de température, il convient de retenir une organisation par valeur croissante ou décroissante à une colonne donnée. Il convient de signaler cette configuration au lecteur.[cite:@Wilke 2019 p57]

** Matrice de bulle #correlation
Ce graphique est une version aggrégée du nuage de bulle et le la matrice de température.

Il simplifie la visualisation des relations entre un couple de variable. A réserver pour un usage d'exploration de donées.[cite:@Sosulski 2019 p51] La taille des bules représente la force de la corrélation. Cette force est la représentation du coefficient de Pearson.[cite:@JSchwabish 2021 p.275]

La couleur peut être utilisée pour distinguer les catégories (à vérifier). Elle peut être également utilisée comme double encodage de la correlation (à vérifier).

Le tableur associée est une matrice de correlation organisant les valeurs de coefficient de Pearson.

** Pareto #correlation
Ce type de graphique montre la relation entre les valeurs quantitatives de catégories organisées en colonne ordonnée et la valeur cumulée affichée en ligne brisée. Le premier point de la ligne vérifiant $$\tau\geq80\%Total$$ est affichée. Est utilisé pour illustrer les éléments important dans un système qualité.

** Arbre de mot #correlation
Représente les liens sémantiques. Utilisé pour classifier les réponses textuelles d'une enquête.(voir Paige Jarreau) Utilisé pour illustrer l'usage des mots dans un texte.(voir Martin Wattenberg & Fernanda Viegas 2007) La taille des mots représente la fréquence de leurs usages.[cite:@JSchwabish 2021 p.316]

** Histogramme #distribution
Utilisé pour afficher une seule distribution de donnée. Il n'y a pas d'espace entre deux barres ce qui permet de favoriser la forme de la distribution. La nature du graphique (barre) implique un calcul d'agrégat pour chaque barre. La largeur de l'agrégat est à évaluer au regard du niveau de détail souhaité. L'histogramme n'est pas adapté à l'affichage de l'ensemble des valeurs, pour cela il convient d'utiliser une courbe de densité.

** Polygone de fréquence #distribution
Utilisé pour afficher simultanément plusieurs distributions de données. Fonctionne comme un histogramme. Chaque agrégat est représenté par un point et ils sont reliés entres eux par un segment droit. Pour faciliter la lécture, il convient de limiter le nombre de distributions affichées à 4 ce qui correspondant notamment au nombre de symboles aisément discriminables.

** Courbe de densité #distribution
La densité représente la probabilité de distribution des variables. [cite:@Sosulski 2019 p48] Pertinent lorsque le nombre de données est très grand, autrement il convient d'utiliser un histogramme.[cite:@Wilke 2019 p62] En cas d'affichage de plusieurs courbe, utiliser  des remplissages transparents pour faciliter la distinctions. L'air de la courbe est usuellement égal à 1 et de ce fait, l'échelle de l'axe des ordonnées dépend de l'axe des absisses.[cite:@Wilke 2019 p63]

** Courbe cumulative #distribution
Utilisé pour représenter une distribution inégale. L'axe des ordonnées est toujours la fréquence cumulative et l'axe des absisses est toujours une mesure.

** Bande de valeur (strip plot) #distribution
Affiche les points de données d'une catégorie. Les points sont légèrement décalés les uns des autres par un offset pour éviter le masquage de données par surimposition. Ce type de graphique peut être associé à un graphique en violon ou en lignes de crêtes lorsque l'on veut exposer graphiquement les données sources des tracés. [cite:@Wilke 2019 p85]

** Boite à moustache #distribution

** Valeur lettrée #distribution
Représente chaque découpage statistique ($$x\sigma$$) par une boite distincte. Convient en remplacement des boites à moustache lorsqu'il y a un très grand nombre de données disponibles. Permet de faire des estimations fiables. [cite:@hofmannLetterValuePlotsBoxplots2017]

** Violon #distribution
Représente fidèlement les distributions d'un très grand nombre de données. Utilisé pour faire des comparaisons entre des catégories. Très pertinent pour représenter les distributions bimodales.[cite:@Wilke 2019 p84] Le tracé du demi-violon est identique au tracé d'une courbe de densité. Celui-ci commence à la valeur la plus petite et termine à la valeur la plus grande.

** Mini-graphe (spark line) #evolution
Affiche la tendance d'évolution d'une variable ou d'une catégorie. Est généralement intégré dans un tableur. N'affiche aucun autre élément que la courbe et un point symbolisant l'état actuel. Cette représentation est très macroscopique et vise à succiter un sentiment plutot que d'exposer une valeur précise. [cite:@JSchwabish 2021 p204]

** Bulle proportionnelle ordonnée #classement
Utilisé pour illustrer les grandes variations de quantité pour différentes catégories et lorsque la distinction des nuances n'est pas primordiale. Les bulles doivent être dimensionnés par leurs surface pour éviter d'éxagérer les différences.[cite:@Schwabish 2021 p123] Ce type de graphique utilise un double encodage de la quantité : la position et la taille. [cite:@Wilke 2019 p120] Bien que ce type de représentation soit considéré comme engageant, il convient d'utiliser un graphique en barre ordonnée à la place lorsque l'évaluation des différences entre catégories est importante.[cite:@Schwabish 2021 p122]

** Barre ordonnée #classement

** Lollipop #classement
Utilisé pour afficher la position dans une liste ordonnée lorsque l'affichage de la valeur est moins important que la position. Egalement très efficace comparé aux barres hordonnées lorsqu'il y a un grand nombre de catégorie dans le classement. Si une ligne connecte le point de la valeur à laxe des ordonnées, l'axe des absisse doit commencer à 0, autrement cela n'est pas obligatoire.

** Haltères #classement
Utilisé pour comparer un minimum et un maximum de plusieurs catégories. La relation entre le maximum et le minimum d'une catégorie est représenté par la barre reliant les deux valeurs.

Peut être utilisé pour illustrer le changement d'une valeur entre deux état données. Dans ce cas, il convient de flécher le sens du changement de l'état antérieur vers l'état final.

Dans ces deux cas de figures, les catégories doivent êtres ordonnées de la plus grande valeur à la plus petite.

Les haltères sont toujours affichés à l'horizontal.

** Pente #classement
Affiche la variation des valeurs ou ratios des catégories entre deux états donnés.

** Bosses #classement
Affiche l'évolution d'un classement entre différents jalons. Ce graphique n'affiche pas les valeurs sous-jacente mais uniquement le positionnement de la catégorie dans le classement.[cite:@Schwabish 2021 p154] Si la valeur source est également à représenter, ce graphique peut se transformer en graphique en ruban, combinant les disposition du graphique en bosse avec celles du graphique de Sankey.[cite:@Schwabish 2021 p154]

* Méthode de sélection

* Etudes futures
Des études complémentaires pourraient être menées sur les sujets suivants :
- La conception de librairies de graphiques accessibles fonctionnant aussi bien dans un usage web que dans les PDF,

* Evolution
La table de donnée sous-jacente doit être organisée par colonne de valeur temporelle croissante.

* Classement
La table de données sous-jacente doit être organisée par ligne de classement croissante (du pemier au dernier en partant de la première ligne).
