#+title: Méthode de sélection, configuration et validation des représentations graphiques des corpus d'informations
#+author: Cyprien PIERRE \orcidlink{0009-0009-9040-6795}
#+EMAIL: cyprien.pierre@eiffage.com
#+DATE: {{{time(%Y-%m-%d)}}}
#+setupfile: "config.org"

#+begin_abstract
\todo[inline]{Rédiger l'abstract}
#+end_abstract

\renewcommand{\keywordsname{\textbf{Mots clés : }\keywords{Visualisation de données, Graphique, Méthode}

#+LaTeX: \begin{multicols}{2}

* Introduction
La visualization de donnée est une discipline ancienne à la littérature riche et précise. Cependant, il n'existe, à ce jour pas de synthèse opérationnelle ni de méthode harmonisée dans la conception des représentations graphiques des informations. Ce rapport vise à fournir un point de départ cohérent à de futurs travaux en représentation visuelle d'informations. Il est basé sur une revue de littérature rigoureuse et les recommendations qu'il porte sont issues des lectures réalisées.

La production d'information réalisée par ordinateur ayant tendance à être perçue comme authentique et fiable, [cite:@stephenfewIntroduction2012] il convient de respecter un certain nombre de rêgles et de bonnes pratiques pour ne pas introduire de biais complémentaires. Nous tentons, à travers ce document, d'objectiver les usages des diverses représentations et leurs configurations.

Le secteur de la construction est historiquement peu digitalisé en comparaison avec les autres industries.[cite:@safurazabidinBibliometricScientometricMapping2020] Pour adresser ce retard, il est important de publier des études opérationnelle claires et industrialisables dont chaque acteur puisse bénéficier immédiatement. Ce rapport s'inscrit dans cette démarche.

L'origine de ces travaux prend place dans un besoin grandissant de solution de visualization d'information dans le secteur de la construction. Les technologies de Big Data, BIM, VDC et les disciplines de la science des données ont fortement pénétré ce secteur sur l'ensemble du cycle de vie des ouvrages. [cite:@asiauniversitytaichungtaiwanResearchApplicationFunctiontechnologyaesthetics2020] L'élaboration de jumeau numérique des bâtiments, l'utilisation renforcée de l'IoT, l'émèrgence des BIS et BOS et l'intégration des solutions d'intelligences artificielles renforcent d'autant plus la nécessité pour ce secteur de se doter de moyens robuste en exploration et en communication des informations.
L'accès à l'information et à sa bonne interprétation permet aux organisations d'adopter une démarche de prise de décision orienté sur les données. [cite:@sosulskiDataVisualizationMade2019]  \todo[inline]{expliquer les enjeux inhérents + références}


Il existe de multiples manières d'interargir avec un graphique. [cite:@schwabishCenteringAccessibilityData2022a;@frankelavskyRightToolsJob2022]

Ce rapport aborde les éléments impliquant la mise en oeuvre de solution programmatique d'accessibilité et pouvant intégrer une logique globale de préparation de graphiques numériques tels que:
- L'exploration visuelle,
- La lecture des tables,
- L'écoute des descriptions,
- La sonification des données,
- L'interractivité avec les commandes de clavier.

Ce rapport n'aborde pas les éléments nécessitant l'emploi de matériels spécifiques tels que :
- L'exploration en réalité étendue,
- L'utilisation de retours haptiques,
- L'emploi d'écran à relief (braille).

* Démarche
La conduite de cette revue s'est déroulé de la manière suivante :
Nous avons commencé par dresser un panorama des types de graphiques existant en nous appuyant sur les travaux de "From Data to Viz"[cite:@yanholtzDataViz2018], "The Graphic Continuum"[cite:@jonathanschwabishGraphicContinuum2014], "Lexique Visuel"[cite:@alansmithLexiqueVisuel], "Insights for ArcGis"[cite:@lindabealeInsightsArcGIS2017].
Cette première action nous a permis de pré-catégoriser les graphiques selon leurs utilisation.

Ensuite, nous avons étudié les livres de divers auteurs et en avons tirés un ensemble de rêgles générales quant à la préparation des graphiques. Cela concerne les aspects visuels (couleurs, polices...), des conseils sur la pertinence dans le choix des types graphiques suivant les objectifs attendus, quelques éléments d'accessibilités et des retours d'expériences. Sur cette base, nous avons affiné la catégorisation préétablies et commencé à regrouper les recommendations.

Pour compléter les dispositions propres à l'accessibilité, nous avons étudié le rapport "Centering accessibility in data visualization". [cite:@schwabishNotHarmGuide2022] Nous en avons tiré un apperçu global des approches possibles pour améliorer l'accessibilité des graphiques ainsi que de nombreux conseils et bonnes pratiques.

En parallele, nous avons étudié diverses chartes de publications issues de divers médias et institutions. Ces lectures nous ont permis de nourrir les reccommendations en matière de conception visuelle des graphiques ainsi que de dresser une liste d'éléments standardisables et d'autres pouvant être laisser libre de personnalisation avec quelques conseils.

Pour finir, nous avons étudié les articles scientifiques publiés sur ces sujets avec une profondeur de recherche à 5 ans. Ce choix de profondeur résulte d'une évolution conséquente depuis le début de la décenie des sciences de l'information. Cetains papiers étudiés sont plus anciens mais ont été très régulièrement cités par d'autres publications et nous avons choisis de les considérer. De cette étape, nous avons affiné les recommendations en identifiant les résultats d'expérimentations.

* Composants
** Polices
Le choix d'une police de texte a de multiples impacts sur la perception des graphiques. Il convient de selectionner une police accessible et de préférence sans sérif pour un usage informatique (Arial, Calibri, Source Sans Pro, Verdana...). [cite:@andreaskrauseBestPracticesData2024] Les polices avec serif peuvent être considérés pour la production d'éléments imprimés. Il n'y a pas de consensus clair sur l'impact des sérifs sur l'accessibilité des polices. [cite:@stephenfewTableDesign2012] Il n'y a pas non plus de consensus clair sur l'efficacité des polices conçues pour adresser des problématiques d'accessibilités telles que la dyslexie. Il convient d'utiliser une police utilisant une hauteur fixe pour les chiffres. [cite:@stephenfewTableDesign2012]

Il est conseillé de restreindre l'utilisation de l'italique car les textes affichés de la sorte sont plus difficiles à lire. Il est également conseillé de limiter l'utilisation de la graisse et du soulignement à des cas spécifiques pour ne pas surcharger les présentations.

La taille de la police joue un role majeur dans l'accessibilité du texte. Il est recommendé d'utiliser une hauteur de police de 12 points.[cite:@andreaskrauseBestPracticesData2024] Le nombre de tailles et de type de police doit être limité en nombre.[cite:@andreaskrauseBestPracticesData2024]

Certaines polices peuvent être utilisés pour projeter des icones (NerdFont, StateFace...).[cite:@jonathanschwabishQualitative2021] L'intérêt des icones est discuté plus tard dans ce rapport.

Il est important de prévoir le chargement de toutes polices non standard (eg. Source Sans Pro, NerdFont...) dans l'interface utilisateur si celles-ci sont utilisées puisqu'elles ne sont probablement pas installées dans le système d'exploitation de l'utilisateur. Prévoir leurs chargement vise à assurer la bonne expérience des utilisateurs.

** Couleurs
L'utilisation de la couleur n'est pas nécessaire pour éditer un graphique efficace. Il s'agit par exemple de la manière la moins efficace pour représenter des différences entre des variables. [cite:@beechamUseGlyphmapsAnalysing2021]

Cependant, utilisé convenablement elle peut aider à la transmission des informations, améliorer la lisibilité de certain graphiques, inscrire une identité visuelle ou encore succiter l'intérêt du lecteur. L'objectif des représentations graphiques des informations étant de maximiser les chances d'acquisition d'une information par un lecteur, il est important de succiter son intérêt en premier lieu. [cite:@asiauniversitytaichungtaiwanResearchApplicationFunctiontechnologyaesthetics2020]

La conception de palettes de couleurs est un exercice difficile. Cette opération implique de considérer les facultées de perception visuelle des utilisateurs mais également le médium et les habitudes associées.

Les études de *(Tran et al)* ont mis en évidence une efficacité particulière de l'utilisation du vert vis à vis du rouge et du bleu dans la vitesse de transmission des informations. L'écart n'est cependant pas suffisement significatif pour justifier à ce titre de l'abandon de l'utilisation de l'une ou l'autre des couleurs.

Pour créer une palette de couleur accessible, celle-ci doit être adaptée à :
- L'achromatopsie et par extension à l'impression en noir et blanc,
- La deutéranopie et à l'utilisation d'écrans lisibles à la lumière du soleil ou d'écrans à gamut restreint,
- La protanopie et à la lécture des couleurs dans un environnement lumineux appauvri en lumière rouge,
- La deutéranomalie et la diffusion sur des écrans non calibrés,
- La protanomalie et à la dégradation des pigments exposés aux UV,
- La tritanopie,
- La tritanomalie,

Des outils comme [[https://gka.github.io/palettes/#/5|s|ce0072,96ffea,00ffad|ffffe0,ff005e,93003a|1|1][Chroma.js]] permettent de vérifier le comportement des palettes de couleurs au regard de certaines affections visuelles.

Elle doit également éviter les biais sociologiques, cognitifs, culturels, et autres tels que le genrage des couleurs,[cite:@andreaskrauseBestPracticesData2024] la perception morale[cite:@rose-greenlandColorPerceptionSociology2016] ou la valeur émotionnelle.[cite:@tranDiscoveringAccessibleData2024]

L'utilisation de la couleur doit également respecter le principe de [cite:@principe sur l'encre de Tufte]. Ainsi, il convient de ne pas remplir les larges zones avec une couleur saturé.[cite:@wilkeCommonPitfallsColor2019] Si un remplissage est requis par le type de graphique, il est préférable d'utiliser des couleurs moins saturés et d'y ajouter de la transparence. [cite:@REF???]

#+caption: Palette d'évidence
#+name: fig:Pal-a
#+attr_latex: :placement [H]
[[./img/palette-evidence.pdf]]

Cette palette de couleur permet d'orienter le regard du lecteur directement sur le segment du graphique important pour l'acquisition de l'information.[cite:@andreaskrauseBestPracticesData2024]

Lors de l'emploi de la palette d'évidence il est important que la couleur de base n'attire pas l'attention. Le focus de l'utilisateur doit rester sur l'élément accentué.[cite:@wilkeColorScales2019]
Le plus efficace est de tracer tous les éléments dans un gris homogène et léger et n'afficher que les valeurs accentuées avec la couleur retenue. [cite:@wilkeColorScales2019]

#+caption: Palette binaire
#+name: fig:Pal-b
#+attr_latex: :placement [H]
[[./img/palette-binaire.pdf]]

Permet de souligner un propos divergent suivant un facteur binaire.[cite:@jonathanschwabishDevelopingDataVisualization2021] 


#+caption: Palette Séquencielle
#+name: fig:Pal-m
#+attr_latex: :placement [H]
[[./img/palette-monochrome.pdf]]

Aussi appelée "monochrome", cette palette de couleur est utilisée lorsque les données sont organisées dans un ordre quantitatif (croissant, décroissant, etc.). [cite:@wilkeColorScales2019;@jonathanschwabishDevelopingDataVisualization2021]

Les variations réalisées en modifiant la lumiosité d'une teinte.[cite:@andreaskrauseBestPracticesData2024] 

En utilisant cette palette de couleur, l'utilisateur perçoit la valeur la plus contrasté (foncé) comme étant la plus haute et inversement. [cite:@kirkDataRepresentation2019]

Il convient d'employer une graduation présente dans l'environnement natuel, partant par exemple d'un bleu foncé et évoluent vers un jaune clair. [cite:@wilkeColorScales2019]


#+caption: Palette de Classement
#+name: fig:Pal-q
#+attr_latex: :placement [H]
[[./img/palette-ranking.pdf]]

Cette palette de couleur est utilisée pour encodé les variations des positions relatives des catégories. La variation s'effectue sur la saturation de la couleur contrairement à la palette [[fig:Pal-m]] qui varie sur la luminosité.

#+caption: Palette thermique
#+name: fig:Pal-t
#+attr_latex: :placement [H]
[[./img/palette-thermique.pdf]]

C'est la température des couleurs qui souligne l'importance des données, du plus froid (faible) au plus chaud (élevé). [cite:@REF???]

En utilisant cette palette de couleur, l'utilisateur donnera plus d'importance aux zones de couleurs chaudes. [cite:@REF???]

#+Caption: Palette divergente
#+name: fig:Pal-d
#+attr_latex: :placement [H]
[[./img/palette-divergente.pdf]]

Cette palette est utilisée pour accompagner la visualisation de la déviation de données dans deux directions opposées à un point central. [cite:@wilkeColorScales2019]

Il convient que les écarts de contraste des deux extrémitées avec le point central soit égal. Il convient également qu'il y ai le même nombre d'échelons colorés de part et d'autre du point central. [cite:@wilkeColorScales2019]

Il convient de ne pas utiliser le rouge et le vert conjointement comme teintes d'extrémités car environ 4% de la population ne peut pas discriminer ces couleurs. [cite:@schwabishCenteringAccessibilityData2022a]

Il convient d'utiliser un vérificateur de couleur pour valider la composition de cette palette.[cite:@andreaskrauseBestPracticesData2024]

#+caption: Palette catégorique
#+name: fig:Pal-c
#+attr_latex: :placement [H]
[[./img/palette-categorique.pdf]]

Ce jeu de couleur est utilisé pour discriminer des catégories et lorsque leurs divergences ou leurs ordre n'est pas important.[cite:@andreaskrauseBestPracticesData2024]

N'employez cette palette de couleur que lorsque les données affichées n'ont aucun lien intrinsèque. [cite:@wilkeColorScales2019]

Chaque couleur doit rester distinguable des autres en toute condition.[cite:@wilkeRedundantCoding2019] Il convient d'utiliser un vérificateur de couleur pour valider la composition de cette palette.[cite:@andreaskrauseBestPracticesData2024]

#+caption: Palette arc-en-ciel
#+name: fig:Pal-x
#+attr_latex: :placement [H]
[[./img/palette-arc-en-ciel.pdf]]

Palette de couleur à prohiber.[cite:@wilkeCommonPitfallsColor2019]

** Graphiques
Pour qu'un graphique s'intègre correctement dans un document, il convient de prévoir une zone de protection. Dans la figure [[fig:ZPR]] nous proposons un exemple de protection relative aux largeurs des marges latérales.

#+caption: Zones de protection d'un graphique
#+name: fig:ZPR
#+attr_latex: :placement [H]
[[./img/general-graphics-rules.pdf]]

*** Cadre
Les lignes d'ages

Les titres d'axes

Les marques d'axes sont utilisées uniquement sur les axes de données quantitatives ou temporelles. Les unitées sont arrondies à une échelle compréhensible. Leurs importance est à atténuer au regard du reste du graphique. [cite:@stephenfewComponentlevelGraphDesign2012]

Les grilles et lignes de guidages sont utiles lorsque les graphiques sont intéractifs. Cependant ils ne doivent pas prendre le dessus sur la représentation des données. [cite:@dougschepersDesigningDataCognitive2022]

*** Ligne
Les lignes sont à différencier les unes des autres en utilisant les méthodologies décrites dans la section [[couleurs]]. Il est possible de surimposer des points de repères lorsque diverses valeurs sont à comparer pour un temps donné. [cite:@stephenfewComponentlevelGraphDesign2012]

Une lignes de tendance peut être utilisée pour aider à la compréhension d'un graphique. Le calcul de moyennes mobiles représente mieux l'évolution des tendances impliquant une évolution temporelle. Dans un nuage de point, cette ligne de tendance peut être droite (meilleur ajustement) ou courbée en fonction des données affichées. Cela doit être considérer lors du tracé. [cite:@stephenfewComponentlevelGraphDesign2012]

Des lignes de références peuvent être utilisées pour indiquer des seuils signicatifs dans le cadre d'une mesure ou d'un suivi de performance. [cite:@stephenfewComponentlevelGraphDesign2012]

*** Annotation
Des annotations peuvent être apposées directement sur le graphique lorsque cela est pertinent pour la communication d'une information spécifique. Si l'annotation n'est pas immédiatement exploitée par le lecteur, elle engendre une diminution de l'efficacité de la lecture du graphique. [cite:@tranDiscoveringAccessibleData2024] Dans ce cas de figure, il faut limiter le nombre d'annotations au strict minimum pour ne pas surcharger le graphique et en conserver sa lisibilité. [cite:@stephenfewComponentlevelGraphDesign2012] Bien que certains lecteurs n'apprécient pas d'être dirigés directement vers une valeur spécifiques, [cite:@tranDiscoveringAccessibleData2024] cette opération reste bénéfique pour des lecteurs ayant des troubles de la visions. [cite:@dougschepersDesigningDataCognitive2022] Nous remarquons, ici, un besoin de personnalisation au regards de préférences utilisateurs.

*** Note
Le créateur d'un graphique peut être ammené à rédiger une note de lecture pour aider à la comprehension du graphique. L'accès à cette note doit être accordé par le mode de présentation du graphique. [cite:@jonathanschwabishDevelopingDataVisualization2021]

Pour une interface numérique, une approche de composition d'interface d'utilisateur avec une étude du mode d'interaction humain-machine est à prévoir.

Pour une présentation imprimée (PDF ou papier), la note doit être imprimé en dessous du titre et de la description du graphique, dans un encart prévu à cet effet.

*** Texte alternatif
Ce type de texte est utilisé pour présenter les graphiques aux utilisateurs employant un logiciel de lecture d'écran. Il n'est pas affiché ni imprimé mais seulement lu par ces logiciels spécialisés.
Les recommendations de cette sections proviennent de l'ouvrage "Centering Accessibility in Data Visualization"[cite:@schwabishNotHarmGuide2022]

La rédaction de ce texte doit fournir une experience similaire à la visualisation du graphique.

Il n'existe pas de norme de rédaction de ces textes descriptifs mais un ensemble de bonnes pratiques sont remarquées. Il existe un écart entre les recommandations mettant en avant la concisions et celle promouvant la précision, la secondes impliquant une rédaction plus complète du texte de remplacement et vise à une meilleure transmission des informations.

En tout état de cause :
- Le titre du graphique n'est pas intégré dans le texte alternatif,
- La description doit être la plus factuelle et neutre possible,
- Les incertitudes et estimations doivent être précisées,
- Il faut éviter toute suggestion de causalité et,
- Ne pas présenter les couleurs et textures.

Suivant l'usage attendu du graphique, les informations à présenter lors de la lecture sont de nature différentes.

#+caption: Contenu type d'un texte alternatif selon l'usage concerné
#+name: fig:alt-txt
#+attr_latex: :placement [H]
[[./img/alt-text.pdf]]

Lorsque les données sont présentées, il convient d'inclure le nom de la variable, son unité et la plage de valeur affichée.

Le texte doit être rédigé en utilisant une ponctuation classique et en évitant les symboles particuliers. Les formules mathématiques sont rédigée de manière litéraire pour éviter les erreurs d'interprétation par les programmes de lectures. Ces textes ne doivent pas comprendre d'URL. Les acronymes doivent être rédigés en majuscule.

La bonne lecture du texte alternatif doit être vérifié.

Une étude future pourrait étudier un parcours utilisateur pour assister à la création des textes alternatifs en employant des modèles de langages, des formulaires et d'autres outils d'interaction humain-machine. Cette étude pourrait également s'intéresser à la mise à jour automatique de ces textes pour les graphiques dynamiques  (mises à jours ponctuelles ou en temps réel).

*** Tableur alternatif
Ce type de table est utilisé en complément du texte alternatif pour exposer les jeux de données affichés dans un graphique aux utilisateurs employant un logiciel de lecture d'écran. Il n'est pas affiché ni imprimé et est uniquement accessible à ces logiciels spécialisés.

Les tables alternatives permettent d'approfondir l'exploration des données exposées sur un graphique par une personne ayant des troubles de la vision. L'exploration de ces éléments doit être proposé et le choix de cette lécture revient à l'utilisateur. [cite:@sarahfossheimCreatingBetterScreen2022]

Des modalitées de navigations à travers ce jeu de données doivent être prises pour améliorer l'interraction humain-machine. Cela peut concerner des solutions propres à la découverte d'information comme la recherche, le filtrage et le classement ou encore des mécanismes de navigations au clavier ou autres. [cite:@sarahfossheimCreatingBetterScreen2022]

*** Jeu de données
Les utilisateurs doivent pouvoir télécharger les données utilisées pour constituer le graphique. Ces données doivent être mises à disposition par un format libre et ouvert tel que le CSV. [cite:@frankelavskyRightToolsJob2022]

** Tableurs
Un tableur permet d'exposer des données brutes organisées en lignes ou en colonnes. [cite:@mikeyiHowChooseRight2020]

Sauf mention contraire, les recommendations sur les tables sont issues du livre "Show me the numbers" de Stephen Few.[cite:@stephenfewShowMeNumbers2012] L'auteur y rentre très en détails sur chaque point de paramétrage. Il y indique notamment les orientations en matière de construction de tableur lorsqu'il s'agit du choix premier d'affichage de données. Ce rapport s'intéresse à la conception de graphique. Dans ce cadre, les tableurs sont des éléments complémentaires pouvant être affichés par l'utilisateur pour explorer plus précisement les données préalablement affichées.

Des prescriptions spécifiques à la préparation de tableurs pour certains graphiques sont apportés le cas échéant dans la suite de ce rapport.

*** Composition
Il est recommendé de séparer les entrées avec un espace vide.
Lorsque les données sont présentées en colonnes, l'espace entre deux colonnes doit être plus grand qu'entre deux lignes,
Lorsque les données sont présentées en ligne, l'espace entre deux ligne doit être plus grand qu'entre deux colonnes,

Insérer une ligne vide toutes les 5 lignes pour faciliter le balayage visuel. [cite:@NFENISO9241-125ErgonomieLinteractionHommesysteme2017]

Utiliser une ligne horizontale pour séparer les entêtes de colonnes des données,

Utiliser une ligne horizontale pour séparer les catégories lorsque les données sont triées par catégories et, ne pas répéter le nom de la catégorie sur toutes les lignes. Les noms des catégories doivent être dans la première colonne, les sous-catégorie dans la seconde colonne, etc. S'il y a plusieurs subdivisions, les noms des catégories doivent être apposées sur la même ligne.

Il convient de rappeler le nom de la catégorie en cas de changement de page et de maintenir la structure du tableur sur toutes les catégories et de rappeler les titres des colones en cas de changement de page.
Les catégories doivent être ordonnées suivant un ordre logique (eg. chronologique, alphabetique, par classement, etc.)

Ne pas effectuer de rotation sur un tableur, son orientation doit respecter celle du texte du document.

Maintenir les aligmnements les titres avecc celui des données en colonnes.

*** Chiffre
Aligner les chiffres à droite.
Homogénéiser les décimales (généralement 2 ou 3 décimales suffisent suivant le contexte).
Indiquer les valeurs négatives avec le symbole moins "-", ici la notion de valeur symbolique est importante. Certains choisissent d'identifier les valeurs négatives entre parenthèses, cependant il ne s'agit pas d'une représentation naturelle répendue pour une telle identification.
Séparer les digit d'un nombre par un espace tous les 3 charactères. Dans le cas de grands nombres, il convient de les arrondir à la précision utile (dixaine, centaine...). Par défaut, la précision affichée doit correspondre à celle de la source d'information.
Si une valeur numérique réfère à une information de catégorie elle doit être traitée comme un texte.

En cas de constat de déviations, utilisez les symboles plus (+) pour les déviations positives, moins (-) pour les déviations négatives et cercle ($\circ$) pour les éléments stables. [cite:@andreaskrauseBestPracticesData2024]

*** Texte
Aligner les textes à gauche.
Centrer les dates et utiliser une convention stricte d'écriture de ces données telles que "YYYY-MM-DD". [cite:@ISO8601-1DateHeureRepresentations2019] La composition de la date doit être indiqué à l'utilisateur. Le choix du format doit respecter le niveau de précision associée à la mesure. Implicitement, le choix d'un formatage de plus haut niveau que la précision de la mesure induit une agrégation des valeurs.
Centrer les données dont la largeur de charactère est fixe.

*** Sommaire et agrégat
Utiliser une ligne verticale pour séparer les valeurs placées en colonne à droite de toutes les valeurs.
Utiliser une ligne horizontale si ces valeurs sont placées en une ligne en bas du tableau.
Si ces valeurs sont le message important de votre tableur, il convient de les affichés imédiatement à droite des colonnes de catégories ou immédiatement en dessous des entêtes de colonnes, suivant la nature du sommaire.

Les produits d'un calcul doivent être affichés dans la colonne imédiatement à droite de la colonne source de données.

Les principales formes sont :
- Moyenne,
- Médiane,
- Dispertion,
- Déviation standard,
- Coefficient de correlation linéaire,
- Taux ou pourcentage.

Lorsque l'on travaille avec des valeurs monétaires il convient de :
- Convertir toutes les valeurs dans une même monaie,
- Corriger les valeurs de l'inflation lorsque l'analyse implique une répartition temporelle.

*** Mise en évidence
Si des valeurs spécifiques doivent être mises en avant, il est possible d'utiliser l'une ou l'autre de ces solutions :
- mettre le texte en gras,
- remplir la cellule d'une couleur.
Il est recommandé de limiter cette opération à un nombre réduit de valeur. Si cela n'est pas possible, il convient de sélectionner un autre mode de visualisation.

* Méthode de sélection
A travers notre revue de litérature, nous avons identifié deux directions pouvant aider à la selection de la meilleure représentation graphique d'informations.

La première est de trier les types de graphiques au regard du type de données qui leurs sont appropriés. Cela implique implicitement que l'utilisateur doit connaitre les données qu'il manipule.

Cela peut représenter un défi pour une population d'utilisateurs d'avantages orientés vers des aspects opérationnels qu'informatiques.

Nous sommes tout de même convaincu que la selection d'un type de graphique doit discretement filtrer les données affichés à l'utilisateurs pour s'assurer du correct emploi du graphique.

La seconde direction est de filtrer les types de graphiques en fonction de l'objectif de l'utilisateur. Nous avons poursuivi notre étude dans ce sens. La figure [[fig:select-filter]] propose un premier niveau de discrimination des types de représentations en identifiant en premier lieu si le graphique doit s'actualiser en temps réel puis en orientant vers des catégories de graphiques au regards de l'objectif recherché.

#+caption: Parcours de sélection initial
#+name: fig:select-filter
#+attr_latex: :placement [H]
[[./img/select-filter.pdf]]

La suite de l'étude présentera, pour chaque catégorie de graphique, un parcours de discrimination supplémentaire.

Pour améliorer l'assistance informatique de l'informatique  à l'utilisateur dans son parcours de conception de graphique, il pourrait être envisager d'étudier la conception d'une interface de requête en langage formel et produisant une proposition de graphique.

Un graphique conçu dans un espace partager d'analyse de donnée peut être difficile à retrouver. Il peut également être affiché dans divers contextes tels qu'une présentation, un rapport ou encore un tableau de bord. Une étude traitant de la récupération d'information associé à une analyse sémantique des graphiques pourrait être menée pour concevoir un système adapté à la recherche d'un graphique existant.
* Méthode de configuration
** Indicateur

#+caption: Séléction d'un graphique d'indicateur
#+name: fig:select-indicateur
#+attr_latex: :placement [H]
[[./img/select-indicateur.pdf]]

*** Marqueur
Affiche une valeur simple, plus pertinent lorsqu'associé à une tendance sur une période donnée. [cite:@mikeyiHowChooseRight2020]

*** Minigraphe
Affiche la tendance d'évolution d'une variable ou d'une catégorie. Est généralement intégré dans un tableur. Un mini-graphe ne possède pas d'axes ni d'autres détails et est composé uniquement d'une courbe et d'un point indiquant la dernière valeur du jeu de donnée. [cite:@sosulskiGraphics2019] Cette représentation est très macroscopique et vise à succiter un sentiment plutot que d'exposer une valeur précise. [cite:@jonathanschwabishDistribution2021]

Un mini-graphe ne possède pas d'axes ni d'autres détails.

*** Tiret
selont Schwabish : inventé par Few

La valeur actuelle mesurée ou calculée est observée au moyen d'une barre horizontale constrastant avec l'arrière plan. [cite:@jonathanschwabishComparingCategories2021]
La valeur cible est représenté par une ligne verticale. [cite:@alansmithLexiqueVisuel]
L'arrière plan expose 3 zones dites qualitative et associées à des notions de performance (eg. inférieur, moyen, bon). [cite:@sosulskiGraphics2019]

Editer une série de tirets permet d'exposer au lecteur diverses comparaisons tout en restant compacte. [cite:@jonathanschwabishComparingCategories2021]

Cette représentation est notamment pertinente lors de la réalisation d'un benchmark. [cite:@mikeyiHowChooseRight2020]
# Définir benchmark

** Composition

#+caption: Séléction d'un graphique de composition
#+name: fig:select-compo
#+attr_latex: :placement [H]
[[./img/select-composition.pdf]]

*** Camembert
Diagramme standard, difficile à lire. [cite:@alansmithLexiqueVisuel]
Limiter à 5 (4?) entrées maximum [cite:@mikeyiHowChooseRight2020]

Ce graphique doit être limité à l'illustration d'un état donnée. Il est important de garder à l'esprit que ce graphique ne donne qu'une représentation et n'est pas adapté à l'affichage de valeurs précises. [cite:@jonathanschwabishParttowhole2021]

Le camembert permet d'accentuer l'appartenance d'une partie individuelle à un ensemble homogène et complet. Il illustre parfaitement des fractions simples.[cite:@wilkeDirectoryVisualizations2019] Les quantités n'ont pas leurs place dans un camembert, ce sont les fractions (taux, pourcentages) qui y sont illustrés. Ainsi, l'ensemble des valeurs constituante sont strictement égale à 100% du total.[cite:@wilkeVisualizingAmounts2019] Il représente plus efficacement les parts dont les angles sont familiers aux lecteurs soit respectivement 90°, 180° et 240° pour les taux 25%, 50% et 75%.

Ce graphine n'est pas adapté à ces cas de figure :
- les parts sont de tailles similaires,[cite:@sosulskiGraphics2019]
- Il y a beaucoup de catégories à afficher pour atteindre l'objectif du message,
- il y a une comparaison entre deux graphiques à réaliser,[cite:@jonathanschwabishParttowhole2021]
- il y a un changement entre plusieurs états.[cite:@wilkeDirectoryVisualizations2019]

Il convient de :
- Arranger les parts par orgre de valeur croissant en commençant à '12h'. [cite:@jonathanschwabishParttowhole2021]
- Utiliser un espace vide entre chaque part pour les faire resortir, [cite:@sosulskiGraphics2019]
- Utiliser une palette de couleur de mise en évidence pour faire ressortir une seule part ou,
- Utiliser une palette de couleur pour faire resortir deux parts,
- Apposer les labels directement sur les parts au moyen d'étiquette. [cite:@sosulskiGraphics2019]

Les parties n'étant pas mises en avant peuvent être agrégée en une catégories "autres". Leurs informations ne servant pas à appuyer le message du graphique. [cite:@jonathanschwabishParttowhole2021]

Dans le cas ou une seule partie de l'ensemble est mise en avant, il est à considérer l'utilisation d'un [[marqueur]]. Le camembert n'apportant aucune information particulière à votre propos.

Il n'est pas encore clairement établis si la comparaison des valeurs est réalisé par la perception des angles ou par la perception des longueurs d'arcs des différentes parties.[cite:@jonathanschwabishParttowhole2021]

Ce diagramme possède un avantage majeur au regard des autres modes de représentation des parties d'un ensemble, il est très populaire et ainsi accessible à usager. [cite:@jonathanschwabishParttowhole2021] Il est également reconnu que les formes circulaires attirent l'intéret des utilisateurs.[cite:@jonathanschwabishParttowhole2021]

*** Donut
Dans un graphique en donut, les valeurs sont à comparer en fonction des longueurs d'arcs.

Comme le diagramme circulaire, le centre peut être utilisé pour afficher un total ou encore une icone. [cite:@alansmithLexiqueVisuel]

# avantage de l'iconographie ?

# avantage de l'estétique ?

Il est, autrement, en tout point similaire aux [[camembert]]

*** Quadrillage
Adapté à l'affichage des informations en pourcentages. Fonctionne mieux avec des entiers naturels. [cite:@alansmithLexiqueVisuel] Généralement en grille de 10 x 10 carrés (pour un total de 100). Chaque carré représente 1% d'un tout. Les carrés sont colorés sur la base de la taille d'une catégorie dans un groupe. [cite:@mikeyiHowChooseRight2020]

*** Treemap
Utilisé pour les relations hiérarchiques d'une partie vers l'ensemble. Difficile à lire s'il y a trop d'éléments affichés. [cite:@alansmithLexiqueVisuel]
Le découpage des boites n'a pas besoin d'être ordonné, il peut y avoir plus de 2 niveaux de hiérarchie. [cite:@mikeyiHowChooseRight2020]

*** Marimeko
Visualisation de la taille et des proportions d'un ensemble homogène de données. [cite:@alansmithLexiqueVisuel]
Exemple : répartition des parts de marché de 3 entreprises sur un axe et taux dans 3 catégories de marché pour chacune

La couleur peut être utilisée pour mettre en évidence une valeur. [cite:@jonathanschwabishComparingCategories2021] Attention au biais de correlation lorsque ce graphique est utilisé pour représenter plusieurs variables. [cite:@jonathanschwabishComparingCategories2021]

*** Voronoi
Semblable à un diagramme de bulle mais transformées en zones dont l'ensemble des points de chacune est plus proche du centre de sa zone que de tout autre centroïde. [cite:@alansmithLexiqueVisuel]

Il est très pertinent pour illustrer les parties d'un ensemble lorsque de nombreuses sous-catégories sont à afficher. [cite:@jonathanschwabishParttowhole2021] En ce sens, il est préféré aux camenberts.

*** Nuage de mots
Affiche des nuages de mots organisés en groupes sémantiques. La taille des mots indique leur fréquence d'utilisation dans le corpus étudié. La couleur des groupes peut représenter un choix de données qualitative (catégorisation). [cite:@sosulskiGraphics2019] Cette visualisation est une méthode d'exploration de texte utile pour réaliser une synthèse macroscopique.
Il convient de filtrer les mots vides dit "stopwords" pour nettoyer la composition des nuages. [cite:@jonathanschwabishQualitative2021] Des listes de mots vides peuvent être trouvées à l'adresse <https://github.com/stopwords-iso/>.

** Classement

#+caption: Séléction d'un graphique de classement
#+name: fig:select-classement
#+attr_latex: :placement [H]
[[./img/select-classement.pdf]]

*** Barre ordonnée
Les catégories sont ordonnées par décroissance de leurs valeurs de quantité[cite:@jonathanschwabishComparingCategories2021] sauf si les catégories on un autre ordre logique (eg. temporel). Dans ce second cas, cet ordre doit être utilisé pour la construction du graphique. [cite:@wilkeVisualizingAmounts2019]

*Note: si catégories temporelles, utiliser un histogramme?*

Lorsqu'un ordre de classement est à afficher, l'utilisation d'un graphique horizontal est à privilégier. [cite:@andreaskrauseBestPracticesData2024]

*William Playfair (1786) pionnier de l'utilisation de ce type de graph ?*

Les barres doivent être affichées à l'horizontal s'il y a beaucoup de valeurs à afficher ou si les labels des catégories s'entrevêchent. [cite:@alansmithLexiqueVisuel;@sosulskiGraphics2019;@wilkeVisualizingAmounts2019;@stephenfewComponentlevelGraphDesign2012;@jonathanschwabishComparingCategories2021]

Il convient de maintenir l'affichage vertical du graphique si les catégories affichées sont des unitées temporelles. [cite:@stephenfewComponentlevelGraphDesign2012]

Ce graphique est plus lisible pour un nombre limité d'entrées. [cite:@mikeyiHowChooseRight2020]

L'espace entre deux barres est égal à la moitié de la largeur d'une barre (ratio 1:0.5). Les barres ont toutes la même largeur. [cite:@stephenfewComponentlevelGraphDesign2012]

Utiliser une couleur homogène à l'ensemble des barres. Une couleur de contraste peut être utilisée pour mettre en évidence certaines catégories.

Ne pas utiliser de motifs de remplissage. Les barres doivent être remplies par un solide coloré. [cite:@stephenfewComponentlevelGraphDesign2012]

Ne pas utiliser de bordures de barres. Ces dernières doivent naturellement contraster avec l'arrière plan.

Si de grands écarts de valeurs empêchent la bonne visualisation des écarts sur une partie du graphique, il est recommendé d'ajouter un second graphique en barre ordonnée n'affichant pas les catégories aux grandes valeurs. [cite:@jonathanschwabishComparingCategories2021]

Ne pas afficher de séparateurs au niveau des catégories, les barres remplissent elles même ce rôle, associées aux espaces entres elles. [cite:@jonathanschwabishComparingCategories2021]

Pour les petits graphiques statiques, il convient d'apposer directement un label à chaque barre contenant la valeur de celles-ci. Par cette action, il convient également de masquer l'axe des absysses. [cite:@jonathanschwabishComparingCategories2021]

Pour les graphiques dynamiques, interractifs ou de grande largeur, il convient d'afficher des lignes d'aide à la lecture en projection des repères de l'axe des valeurs. Ces lignes doivent être faiblement contrastées et être tracées en arrière plan des barres. [cite:@jonathanschwabishComparingCategories2021]

Ne pas segmenter les barres. [cite:@jonathanschwabishComparingCategories2021]

Ne pas ajouter d'iconographie aux barres. [cite:@tranDiscoveringAccessibleData2024]

*** Lollipop
Utilisé pour afficher la position dans une liste ordonnée lorsque l'affichage de la valeur est moins important que la position. [cite:@alansmithLexiqueVisuel] Egalement très efficace comparé aux barres hordonnées lorsqu'il y a un grand nombre de catégorie dans le classement. [cite:@mikeyiHowChooseRight2020]  Si une ligne connecte le point de la valeur à laxe des ordonnées, l'axe des absisse doit commencer à 0, autrement cela n'est pas obligatoire.

*** Haltères
Utilisé pour comparer un minimum et un maximum de plusieurs catégories. [cite:@alansmithLexiqueVisuel] La relation entre le maximum et le minimum d'une catégorie est représenté par la barre reliant les deux valeurs. [cite:@mikeyiHowChooseRight2020]

Peut être utilisé pour illustrer le changement d'une valeur entre deux état données. Dans ce cas, il convient de flécher le sens du changement de l'état antérieur vers l'état final.

Dans ces deux cas de figures, les catégories doivent êtres ordonnées de la plus grande valeur à la plus petite.

Les haltères sont toujours affichés à l'horizontal.

*** Bosses
Affiche l'évolution d'un classement entre différents jalons. [cite:@mikeyiHowChooseRight2020;@alansmithLexiqueVisuel]  Ce graphique n'affiche pas les valeurs sous-jacente mais uniquement le positionnement de la catégorie dans le classement. [cite:@jonathanschwabishTime2021] Si la valeur source est également à représenter, ce graphique peut se transformer en graphique en ruban, combinant les disposition du graphique en bosse avec celles du graphique de Sankey. [cite:@jonathanschwabishTime2021]

*** Barre empilée
Représente le total de chaque catégorie et la proportion de leurs composantes. Les composantes doivent être homogènes. Si les proportions sont plus importantes que les totaux, considérer d'utiliser l'affichage empilée à 100%. [cite:@mikeyiHowChooseRight2020]

Seule la catégorie ayant sa base à 0 sera facile à comparer pour le lecteur car les autres ne partagent pas la même base.[cite:@jonathanschwabishComparingCategories2021] Il est préférable de tracer chaque diagramme de barre dans un grapgique distinct et des les disposer en [[matrice de graphique]]. [cite:@jonathanschwabishComparingCategories2021]

*** Barre jumelée
Permet d'afficher plusieurs séries. Devient plus difficile à lire avec plus de deux séries. [cite:@alansmithLexiqueVisuel]
Les barres d'une même catégories sont collées les unes aux autres pour souligner leurs appartenance à une même catégorie (ratio 1:0). Espacer les jeux de barres jumelées d'une largeur égale à une barre (ratio n:1).

Les barres sont colorées avec une palette de couleur de catégories. Les couleurs sont utilisées pour distinguées chaques barres dans une catégories, les couleurs doivent être homogènes pour chaque catégorie. Si les différentes valeurs affichées sont d'importances similaires, il convient d'utiliser une palette de couleurs à faibles contrastes. N'utiliser qu'une seule couleur par ensemble de données apparentées. [cite:@stephenfewComponentlevelGraphDesign2012]

*** Pente
Affiche la variation des valeurs ou ratios des catégories entre deux états donnés. [cite:@alansmithLexiqueVisuel]

*** Coordonnées parallèles
Montre en simultané la valeur et la relation de catégories hétérogènes pour plusieurs systèmes. [cite:@jonathanschwabishRelationship2021] Permet de valoriser la valeur. [cite:@alansmithLexiqueVisuel]

Pratique pour observer les schémas et relations entre les systèmes. [cite:@mikeyiHowChooseRight2020] Ce graphique est plus efficace pour explorer des jeux de données que pour les présenter à un audimat. [cite:@sosulskiGraphics2019]

Chaque axes de catégories peut avoir sa propre échelle. Cela représente mieux les valeurs de chaque catégorie mais cela implique également de bien labeliser les axes pour distinguer leurs échelles. [cite:@jonathanschwabishRelationship2021]

Afficher un grand nombre de jeux de données sur un même graphe risque de le rendre illisible. [cite:@jonathanschwabishRelationship2021] Dans ce cas il convient d'utiliser une palette de couleur de mise en évidence et de selectionner un ou deux jeux de données à mettre en avant.

Lors de l'exploration d'un jeu de donnée à travers une interface informatique, il convient de mettre en avant la ligne pointée par l'utilisateur et de labeliser chaque points de catégorie avec la valeur associé. [cite:@sosulskiGraphics2019]

*** Radar
Représentation compacte de la valeur de variables hétérogènes pour un seul système. [cite:@alansmithLexiqueVisuel] Les radards sont utilisés pour identifier les variables ayant des valeurs similaires et les exceptions. [cite:@sosulskiGraphics2019]

La représentation des valeurs se fait à travers la forme globale du polygonne. Il convient de coloriser l'interrieur de celui-ci pour bien faire ressortir sa forme. [cite:@jonathanschwabishRelationship2021]

Utiliser une disposition en small-multiples plutot que de surimposer plusieurs polygones de valeurs. [cite:@jonathanschwabishRelationship2021]

La représentation des variables est fortement correlé à la forme du polygone plutot qu'aux valeurs des sommets. [cite:@sosulskiGraphics2019] De ce fait, pour améliorer la forme du polygonne et offrir une représentation avec le moins de distortions possibles, il convient d'homogénéiser les échelles des axes.

*** Ligne de crête
Ce graphique représente des courbes de densité séparées par un offset et est utilisé pour comparer la distribution d'une vrariable entre des catégories. [cite:@wilkeVisualizingManyDistributions2019] Parfait lorsque les schémas de distributions sont bien distincts entre les groupes. [cite:@mikeyiHowChooseRight2020] Cela évite que les courbes de densités des catégories s'entrevêchent.[cite:@jonathanschwabishDistribution2021]

Ce graphique se met très bien à l'échelle de grands jeux de données. [cite:@wilkeVisualizingManyDistributions2019]

Il est adapté à :
- la comparaison des changements de distributions à travers le temps [cite:@wilkeDirectoryVisualizations2019] associé à un gradiant de couleur pour diriger le regard vers la distribution la plus récente, [cite:@jonathanschwabishDistribution2021]
- la comparaison des évolutions de deux tendances à travers le temps. [cite:@wilkeVisualizingManyDistributions2019] associé à une palette de couleur binaire.

L'axe des absysses affiche la valeur de réponse et l'axe des ordonnées affiche les catégories. [cite:@wilkeVisualizingManyDistributions2019]

Il convient de classer les catégories suivant un ordre logique. [cite:@jonathanschwabishDistribution2021] Voir (insérer renvois ici vers l'explication de la logique de classement de catégories)

Il est possible d'afficher les barres d'erreurs dans les lignes de crêtes. Ce mode de représentation s'appel un "demi-oeil". [cite:@wilkeVisualizingUncertainty2019]

Il est possible d'afficher les nuages de points dont l'estimation de la courbe de densité est issue. Ceux-ci sont affichés en dessous des courbes de densité. Cette forme de représentation est appelé "Nuage de pluie". (ref: Micah Allan ou Schwabish2021p212) Cette représentation offre à la fois une représentation générique et une visualisation précise des données. [cite:@jonathanschwabishDistribution2021] Bien que cette représentation soit très efficace, elle n'est pas très répendue. [cite:@jonathanschwabishDistribution2021] Il faut être vigilent à bien expliquer son fonctionnement lors de son utilisation dans un rapport. Dans le cas d'un nuage de pluie, il faut faire attention à ce que les points de données n'entre pas en surimposition avec les courbes de densitées tracées en dessous.
*** Matrice de graphique
Popularisé par E. Tufte

Est utilisé pour comparer de multiples graphiques homogènes organisées en matrices. Chaque entité affiche le graphique d'une catégorie. Les graphiques sont tous à la même échelle. [cite:@sosulskiGraphics2019]

Conseils : Limitez les détails dans chacun des graphique. [cite:@sosulskiGraphics2019] Regroupez les axes pour n'afficher qu'un seul axe Y par ligne et un seul axe X par colonne.

Interractivité : pouvoir explorer l'ensemble des graphiques simultanéments (eg. cible en croix '+' au niveau du point de donnée pointé répliqué dans les autres graphiques)

#+caption: Composition d'une matrice de graphique
#+name: fig:Compo-small-multiple
#+attr_latex: :placement [H]
[[./img/small-multiple.pdf]]

** Distribution

#+caption: Séléction d'un graphique de distribution
#+name: fig:select-distribution
#+attr_latex: :placement [H]
[[./img/select-distribution.pdf]]

*** Courbe de densité
La densité représente la probabilité de distribution des variables. [cite:@sosulskiGraphics2019] Pertinent lorsque le nombre de données est très grand, autrement il convient d'utiliser un histogramme. [cite:@wilkeVisualizingManyDistributions2019] En cas d'affichage de plusieurs courbe, utiliser  des remplissages transparents pour faciliter la distinctions. L'air de la courbe est usuellement égal à 1 et de ce fait, l'échelle de l'axe des ordonnées dépend de l'axe des absisses. [cite:@wilkeVisualizingManyDistributions2019]

*** Violon
Représente fidèlement les distributions d'un très grand nombre de données. [cite:@alansmithLexiqueVisuel] Utilisé pour faire des comparaisons entre des catégories. [cite:@mikeyiHowChooseRight2020]  Très pertinent pour représenter les distributions bimodales. [cite:@wilkeVisualizingManyDistributions2019] Le tracé du demi-violon est identique au tracé d'une courbe de densité. Celui-ci commence à la valeur la plus petite et termine à la valeur la plus grande.

*** Histogramme
Utilisé pour afficher la fréquence d'une variable simple regroupée en intervale de fréquence (agrégat).[cite:@sosulskiGraphics2019] Il affiche ainsi une distribution statistique de donnée. Il n'y a pas d'espace entre deux barres (ratio 1:0) ce qui permet de favoriser la forme de la distribution. [cite:@alansmithLexiqueVisuel]

# #+caption: Composition d'un histogramme
# #+name: fig:Compo-histogram
# #+attr_latex: :placement [H]
# [[./img/histogram-compo.pdf]]

La nature du graphique (barre) implique un calcul d'agrégat pour chaque barre. [cite:@wilkeVisualizingDistributionsHistograms2019] La largeur de l'agrégat est à évaluer par le concepteur au regard du niveau de détail souhaité.[cite:@wilkeVisualizingDistributionsHistograms2019]

# #+caption: Sélection des rêgles de définitions des agrégats
# #+name: fig:histo-agregats
# #+attr_latex: :placement [H]
# [[./img/histogram-agregats.pdf]]

L'utilisation d'un histogramme permet d'identifier des schémas de distributions tels que définis dans la figure [[fig:Patterns-histogram]]. [cite:@jonathanschwabishDistribution2021]
Ces schémas sont dit :
- *Incliné à gauche* lorsque les données sont majoritairement sur la gauche du graphique,
- *Incliné à droite* lorsque les données sont majoritairement sur la droite du graphique,
- *Symétrique* quand il y a approximativement égal de valeurs de chaque coté d'une valeur centrale,
- *Bimodale* lorsque deux pics de valeurs sont constatables,
- *Multimodale* lorsque plus de deux pics de valeurs sont constatables,
- *Uniforme* quand toutes les valeurs sont distribuées de façon globalement homogène.

#+caption: Illustration des formes remarquables d'un histogramme
#+name: fig:Patterns-histogram
#+attr_latex: :placement [H]
[[./img/histogram-patterns.pdf]]

# Les variantes de l'histogrammes :
# #+caption: Illustration des variantes de l'histogramme
# #+name: fig:Variantes-histogram
# #+attr_latex: :placement [H]
# [[./img/histogram-variantes.pdf]]

L'histogramme n'est pas adapté aux cas suivant :
- l'affichage de l'ensemble des valeurs, pour cela il convient d'utiliser une [[courbe de densité]]. [cite:@wilkeVisualizingDistributionsHistograms2019]
- s'il y a peu de valeurs dans le jeu de données, [cite:@weissgerberBarLineGraphs2015] préférez l'utilisation d'une [[bande de valeur]].
- l'affichage de plusieurs distributions,[cite:@wilkeVisualizingDistributionsHistograms2019] utilisez une décomposition en [[matrice de graphique]].

*** Valeur lettrée
Représente chaque découpage statistique (\(x\sigma\)) par une boite distincte. Convient en remplacement des boites à moustache lorsqu'il y a un très grand nombre de données disponibles. Permet de faire des estimations fiables. [cite:@hofmannLettervaluePlotsBoxplots2017;@mikeyiHowChooseRight2020 ]

*** Boite à moustache
Résume les distributions multiples en montrant la médiane et l'étendue des données. [cite:@alansmithLexiqueVisuel]

Ce graphique est plus efficace lorsqu'il y a de nombreuses mesures pour une entrée et que leur distribution doit être représentée (eg : mesure médiane, basse, haute, incertitude...). [cite:@mikeyiHowChooseRight2020]

Les lignes s'étendant au dessus et en dessous sont appelées les moustaches. [cite:@wilkeVisualizingManyDistributions2019]

*Voir trx de son inventeur : John W. Tukey*

Il est possible d'afficher la position d'un point précis du jeu de donnée sous-jacent. (couleurs mise en évidence ?)

Les boites à moustaches suivent les dispositions graphiques des barres ordonnées. [cite:@stephenfewComponentlevelGraphDesign2012]

*** Carte de fréquentation
Excellente visualisation pour suivre la fréquence d'une activité. Favorise la quantité à la qualité (exemple : github). [cite:@alansmithLexiqueVisuel]

** Evolution

#+caption: Séléction d'un graphique d'évolution
#+name: fig:select-evolution
#+attr_latex: :placement [H]
[[./img/select-evolution.pdf]]

*** Jauge
Les jauges sont des représentations familières et facile à lire. [cite:@jonathanschwabishComparingCategories2021] En ce sens, elles sont pertinente pour afficher des données. Cependant, il convient de s'intéresser particulièrement à leurs représentation métaphorique. Les graphiques en jauge étant un skeumorphisme, leurs utilisation est probablement plus pertinente pour l'affichage d'information pour lesquelles elles sont utilisées dans le monde physique.

Cela concerne par exemple :
- L'affichage d'une vitesse instantanée,
- L'affichage d'une pression instantanée et par extension,
- L'affichage d'un niveau dans un réservoir.

Pour tout autre usage, et considérant la difficulté humaine d'interprétation d'une valeur en comparant des angles ainsi que le manque d'options pertinentes pour ajouter des informations qualitatives sur les jauges, il convient d'utiliser un graphique en [[Tiret]].

*** Ruisseau
Vérifier la métaphore liée au nom

A privilégier lorsque la visualisation des changements en proportions au fil du temps est plus importante que les valeurs individuelles. [cite:@alansmithLexiqueVisuel]

*** Horizon
Permet de vérifier un équilibre entre deux borne par rapport à une base. [cite:@alansmithLexiqueVisuel]  Utilisé pour suivre l'évolution d'une variable dans le temps et devant respecter un écart-type (eg. tension à 230V +/- 5%). L'information la plus importante est le dépassement de l'écart-type. Pour correctement mettre en évidence ces phénomènes, il est recommendé d'utiliser une palette de couleur de

*** Sismogramme
Pour montrer des séries à grandes variation dans les données. [cite:@alansmithLexiqueVisuel]

*** Ligne
Inventé par Playfair en 1786 [cite:@sosulskiBecomingVisual2019]
Représentation graphique standard et famillière pour la représentation des séries temporelles. [cite:@alansmithLexiqueVisuel,@Schwabish2021p86]

Les lignes relient chaque point de mesure. Pour de grands jeux de données, il convient d'utiliser une ligne lissée sur l'ensemble du graphique plutot qu'une ligne brisée par chaque point de donnée. [cite:@wilkeDirectoryVisualizations2019]

La base des ordonnées doit être égale ou inférieure à la plus faible valeur affichée. [cite:@wongWallStreetJournal2010]

Il n'existe pas de rêgle stricte quand à la limite de séries affichables sur un graphique.[cite:@jonathanschwabishTime2021] Il convient de s'intéresser à la perception du lecteur recherché par le concepteur pour arbitrer les choix : [cite:@jonathanschwabishTime2021]
- En cas d'impression, limiter le nombre de lignes simultanées à 4 au maximum, [cite:@wongWallStreetJournal2010]
- Si l'interraction est possible avec le graphique, il est possible de tracer toutes les lignes dans un même graphique à condition d'utiliser un système de mise en évidence,[cite:@jonathanschwabishTime2021]
- Ces cas échouant, séparez les lignes et tracez une [[matrice de graphique]].

Ne pas utiliser ce graphique pour essayer d'illustrer une différence entre deux courbes. [cite:@jonathanschwabishTime2021]

Les axes doivent être labelisé (obligatoirement le titre de la série, optionnellement la valeur finale) directement en fin de ligne, à droite du graphique. [cite:@andreaskrauseBestPracticesData2024;@sosulskiGraphics2019]

Il est possible de mettre en évidence un point spécifique en utilisant un symbole (de préférence un cercle plein) et en y apposant une étiquette affichant \(f(x)=y\).

La distinction des séries est plus efficace en utilisant des teintes différentes. Dans ce cas, il convient également d'utiliser des tons différents pour assurer le maintiens des distinctions si le graphique est imprimé en nuance de gris. [cite:@stephenfewComponentlevelGraphDesign2012]
Il convient également de n'utiliser que des lignes continues pour les tracés. [cite:@stephenfewComponentlevelGraphDesign2012]
L'utilisation de symboles comme éléments différenciants entre les séries n'est pas pertinent. [cite:@stephenfewComponentlevelGraphDesign2012]

La plage allant de la plus petite à la plus grande valeur occupe entre 70 et 80% de l'espace vertical dans le graphique.[cite:@mikecisnerosWhatLineGraph2024]

** Correlation

#+caption: Séléction d'un graphique de correlation
#+name: fig:select-corellation
#+attr_latex: :placement [H]
[[./img/select-correlation.pdf]]

*** Pareto
Ce type de graphique montre la relation entre les valeurs quantitatives de catégories organisées en colonne ordonnée et la valeur cumulée affichée en ligne brisée. Le premier point de la ligne vérifiant \(\tau\geq80\%Total\) est affichée. La zone précédent ce point est mise en évidence.
Est utilisé pour illustrer les éléments important dans un système qualité.

*** Nuage de point

Représente la relation entres deux variables continues. [cite:@alansmithLexiqueVisuel]
La couleur est la meilleure façon de distinguer les catégories.[cite:@stephenfewComponentlevelGraphDesign2012] Pour cela, utilisez la pallette catégorique ([[fig:Pal-c]])

Dans un maximum de 3 catégories de données, il est possible d'utiliser un double encodage combinant une forme et une couleur.[cite:@andreaskrauseBestPracticesData2024]

les formes recommandées sont :

#+caption: Formes des points de données
#+name: fig:formes
#+attr_latex: :width 3.2cm :placement [H]
[[./img/formes.pdf]]

Leur avantage est qu'elles n'ont pas de connotation intuitive.[cite:@andreaskrauseBestPracticesData2024] (retirer la croix?)

Si des milliers de point de données sont à afficher, il est préférable d'utiliser soit :
- des cercles ouverts,
- des petits cercles,[cite:@stephenfewComponentlevelGraphDesign2012]
- des cercles avec une transparence.[cite:@stephenfewComponentlevelGraphDesign2012]

  Cela permet de limiter le masquage des points de données par surimposition. [cite:@andreaskrauseBestPracticesData2024]

*** Nuage de bulle
Il s'agit d'un nuage de point dont la taille des bules est utilisé pour représenter une troisieme valeur quantitative. [cite:@alansmithLexiqueVisuel]

*** Matrice de bulle
Ce graphique est une version aggrégée du nuage de bulle et le la matrice de température.

Il simplifie la visualisation des relations entre un couple de variable. A réserver pour un usage d'exploration de donées. [cite:@sosulskiGraphics2019] La taille des bules représente la force de la corrélation. Cette force est la représentation du coefficient de Pearson. [cite:@jonathanschwabishRelationship2021]

La couleur peut être utilisée pour distinguer les catégories (à vérifier). Elle peut être également utilisée comme double encodage de la correlation (à vérifier).

Le tableur associée est une matrice de correlation organisant les valeurs de coefficient de Pearson.

*** Carte de température
Représentation graphique d'une table de valeur homogène. [cite:@sosulskiGraphics2019]
Intéressante pour afficher une tendance lorsqu'un très grand nombre d'information est impliqué.

Ce graphique utilise les couleurs de la palette thermique [[fig:Pal-t]].

L'organisation des catégories changeant la forme de la matrice de température, il convient de retenir une organisation par valeur croissante ou décroissante à une colonne donnée. Il convient de signaler cette configuration au lecteur. [cite:@wilkeVisualizingAmounts2019]

L'emplois de solutions d'intéractivité permet une meilleure découverte des données affichées.

*** Arbre de mot
Représente les liens sémantiques.
Utilisé pour classifier les réponses textuelles d'une enquête.(voir Paige Jarreau)
Utilisé pour illustrer l'usage des mots dans un texte.(voir Martin Wattenberg & Fernanda Viegs 2007)
La taille des mots représente la fréquence de leurs usages. [cite:@jonathanschwabishQualitative2021]

** Déviation

#+caption: Séléction d'un graphique de déviation
#+name: fig:select-deviation
#+attr_latex: :placement [H]
[[./img/select-deviation.pdf]]

*** Alluvial

Montre les changements sur un flux entre un état et au moins un autre. Adapté au traçage d'un processus complexe. [cite:@alansmithLexiqueVisuel]

Cette représentation découpe un ensemble en quantité individuelles de plusieurs catégories. Les bandes sont tracées entre chaque catégories pour représenter leurs relations. La largeur des bandes indiquent la proportion des catégories correllées les unes aux autres. [cite:@wilkeVisualizingNestedProportions2019]

A utiliser à la place des mosaiques et treemaps lorsqu'il y a plus de deux variables de regroupement des données. [cite:@wilkeDirectoryVisualizations2019]

*** Bande de valeur
Affiche les points de données d'une catégorie.[cite:@jonathanschwabishDistribution2021] Les valeurs peuvent être affichés par des lignes ou des cercles pleins mais les cercles sont à privilégier lorsqu'il est nécessaire de déagglomérer les données.

Il est possible d'utiliser de la transparence pour illustrer les zones de valeurs compactes. [cite:@jonathanschwabishDistribution2021] Utilisez la palette de couleurs divergentes [[fig:Pal-d]] pour mettre en évidence la répartition des valeurs mesurées et souligner la séparation de celles ci par rapport à un axe de référence.[cite:@jonathanschwabishDistribution2021]

Les points peuvent être légèrement décalés les uns des autres par un offset pour éviter le masquage de données par surimposition. Ce mode de représentation est appelé "essaim d'abeille" (beeswarm). [cite:@jonathanschwabishDistribution2021]

# -----à creuser-----
Histopoint : Wilkinson dot plot (Leland Wilkinson) Affichage des bandes de valeurs pour chaque agrégat d'un histogramme.[cite:@jonathanschwabishDistribution2021]

Epis de blé : Wheat plot (SFew)

*** Barre divergente
Affiche correctement un ensemble de valeur quantitative triées par catégories lorsque des valeurs négatives sont utilisées. [cite:@alansmithLexiqueVisuel] L'axe des absysse doit être égal à 0 et toutes les barres doivent être projetées depuis cet axe.

*** Barre divergente empilée
Utilisé pour illustrer les résultats d'enquêtes impliquant un sentiment. [cite:@alansmithLexiqueVisuel] Les barres doivent être calculées en pourcentage et alignées à 100% comme pour une partie d'un ensemble. Les réponses sont affichées de façon ordonée et du plus négatif au plus positif. Il convient d'utiliser une palette de couleur divergente. Lors de la préparation d'une enquête impliquant des sentiment, il est conseiller de proposer un choix de valeur paires pour éviter les votes neutres sauf si la représentation de l'indiférence est une volontée de l'étude. De plus, *expliquer la limite de nombre de zones facile à visualiser* (max 6?)

*** Cascade
Affiche les gains et pertes entres deux états d'un système. [cite:@jonathanschwabishComparingCategories2021] Utilisé principalement pour les analyses financières. [cite:@alansmithLexiqueVisuel]

*** Chandelier
Affiche des bilans quotidiens (eg. ouverture, fermeture, point haut, point bas). [cite:@alansmithLexiqueVisuel]
La couleur est utilisée pour représenter la direction de l'évolution de la valeur (augmente, descend).

Illustre les évolutions d'un stock sur une temporalité donnée. La ligne indique l'état le plus haut et l'état le plus bas de la journée. La barre indique l'état de l'ouverture et de la cloture de la période. [cite:@jonathanschwabishDistribution2021] Il convient d'utiliser une palette de couleur binaire pour contraster les périodes aux soldes positifs des périodes aux soldes négatifs.

*** Colonne vertébrale
Utilisé pour afficher la quantité de réponses négatives et positives à une question. Le spine divise une valeure quantitative unique en deux composants distinct contrasté par un déterminent binaire. [cite:@alansmithLexiqueVisuel] Utilisé pour afficher la quantité de réponses négatives et positives à une question.

*** Courbe cumulative
Utilisé pour représenter une distribution inégale. L'axe des ordonnées est toujours la fréquence cumulative et l'axe des absisses est toujours une mesure. [cite:@alansmithLexiqueVisuel]

*** Eventail
Utilisé pour montrer l'incertitude des projections futures. [cite:@alansmithLexiqueVisuel]

*** Nuage de point connecté
Ce graphique est utilisé pour représenter les mouvements entre des étapes. Il permet d'identifier des schémas de progressions comme des cycles et des irrégularités qui seraient difficiles de remarquer autrement. [cite:@wilkeVisualizingTimeSeries2019]

Lors de l'utilisation de ce type de graphique, il convient d'indiquer la direction ainsi que la temporalité étudiée. [cite:@wilkeVisualizingTimeSeries2019]

Pour souligner la direction de l'évolution entre deux points il est possible de :
- Flécher la direction de l'évolution entre deux points si les points sont bien espacés et qu'un seul jeu de donnée est affiché, [cite:@jonathanschwabishComparingCategories2021]
- Utiliser un gradiant de couleur du plus clair vers le plus foncé.[cite:@wilkeVisualizingTimeSeries2019]

La temporalité devrait être indiquée dans le titre du graphique ou au moyen d'éléments de l'interface utilisateur.

Comme ce graphique sert à synthétiser des variations de valeurs, il est préférable de l'utiliser pour afficher des jeux de données dont la variation n'est pas mesurée régulièrement pour éviter d'avoir trop de points à relier et donc d'éviter de créer un graphique trop encombré. [cite:@jonathanschwabishComparingCategories2021]

Un exemple d'utilisation du nuage de point connecté : `https://share.stateofjs.com/share/prerendered?localeId=en-US&surveyId=state_of_js&editionId=js2024&blockId=tools_arrows&params=&sectionId=libraries`

*** Sankey
Créé par : Matthew Henry Phineas Riall Sankey (1898)

L'épaisseur représente la part d'un évènement. Chaque flèche représente l'entrée ou la sortie d'élément sur le système étudié. [cite:@mikeyiHowChooseRight2020]

Les changements sont liés à une évolution temporelle et à l'association de catégories. La force de ce graphique est qu'aucun de ces deux aspect ne pévaut sur l'autre. [cite:@jonathanschwabishComparingCategories2021]

Très utile pour représenter les flux entre des catégories ou entre des états. [cite:@jonathanschwabishComparingCategories2021]

Il convient néanmoins de limiter le nombre de catégorie  affiché pour maintenir un bon niveau de lisibilité. [cite:@jonathanschwabishComparingCategories2021]

Variante : "Echanges, corde"

Illustre les flux bidirectionnels et le gagnant net dans une matrice. [cite:@alansmithLexiqueVisuel]

Dans la mesure du possible, il convient de flécher le sens du flux.

Ce diagramme incite les utilisateurs à l'explorer plus en détail. [cite:@jonathanschwabishRelationship2021]

* Méthode de validation
Comme tout élément informatique, un graphique doit être vérifier et valider. Cela est d'autant plus nécessaire si la production de graphique est intégré à un pipeline de donnée.

En premier lieu, il convient de vérifier l'abscence de "distortion" des données affichées pour limiter les biais inhérents.[cite:@stephenfewGeneralGraphDesign2012]

$$LieFactor=\abs{\frac{\frac{\Delta VisualLength}{VisualStartLength}}{\frac{\Delta Data}{DataStart}}}$$
[[https://www.labo.mathieurella.fr/?p=395][source]]

Références à Sosulski & Tufte : Lie Factor

Pour définir un cadre de validation des graphiques, nous avons étudié les personas mis à disposition par Will Soward à travers le site web "Neurodiversity Design System".[cite:@NeurodiversityDesignSystem]

De cette étude, nous avons extrait des éléments généraux et d'autres pouvant faire l'objet d'un choix de personnalisation de l'utilisateur. Le tableau [[table:persona]] les identifies.

#+caption:Résumé des attentes utilisateurs
#+name: table:persona
#+attr_latex: :float multicolumn
| N° | Besoins                          | Niveau d'implémentation | Référence CIM-10            |
|----+----------------------------------+-------------------------+-----------------------------|
| 01 | Absence d'animation              | Personnalisé            | F84, F90, G40-G41           |
| 02 | Absence de distraction           | Personnalisé            | F84, F90                    |
| 03 | Adapté au thème sombre           | Tous les utilisateurs   | F84, G40-G41, G43           |
| 04 | Adapter la langue                | Personnalisé            | N/A                         |
| 05 | Aide contextuelle                | Personnalisé            | F70-F79                     |
| 06 | Concision des informations       | Personnalisé            | F84                         |
| 07 | Données claires et factuelles    | Tous les utilisateurs   | F70-F79                     |
| 08 | Explication d'utilisation        | Personnalisé            | F70-F79                     |
| 09 | Facilité d'accès à l'information | Tous les utilisateurs   | F70-F79, F90                |
| 10 | Facilité de compréhension        | Tous les utilisateurs   | F70-F79                     |
| 11 | Facilité d'utilisation           | Tous les utilisateurs   | F70-F79, F84                |
| 12 | Lecture par logiciel             | Personnalisé            | R48, H53, H54               |
| 13 | Réduire la luminosité            | Personnalisé            | F84, H53, H54, G40-G41, G43 |
| 14 | Rétrocompatibilité               | Tous les utilisateurs   | N/A                         |

Les références CIM-10 mensionnées dans le tableau [[table:persona]] sont : les troubles du langage (R48), les troubles de déficience cognitive (F70-F79), les troubles du spectre autistique (F84), les troubles du déficit de l'attention avec ou sans hyperactivité (F90)  les troubles de la vision (H53), les déficits de la vision (H54), les affections épiléptiques (G40-G41) et migraineuses (G43).

La capacité de modifier la langue par défaut vise à limiter la barrière de la langue. Dans le même ordre, la rétrocompatibilité vise à limiter la fracture numérique. \todo[inline]{trouver si possible des lois ou travaux apparentés d'orientation de ces considérations}

* Etudes futures
Des études complémentaires pourraient être menées sur les sujets suivants :

La conception de librairies de graphiques accessibles et fonctionnant aussi bien dans un usage web que dans les PDF.
  
* Evolution
|    Date | Changements           |
|---------+-----------------------|
| 2025-02 | Rédaction du document |

* Glossaire
# Fixer la position, l'export
# #+include: ~/org/glossary.org
# #+print_glossary: :type glossary

* Acronymes
# #+print_glossary: :type acronyms

* Références
# Séparer les entrées de bibliographie (Livres, Infographies, Normes, Articles, Divers)
# Associer les chapitres de livres aux livres sources (crossref in biblatex)
#+print_bibliography: :heading none

#+LaTeX_HEADER: \end{multicols}
